Practise on data cleaning.

In [31]:
import pandas as pd
import numpy as np

In [32]:
kl_house = pd.read_csv("C:/Users/PENGGUNA/Desktop/Mira/CADS/kl_house_dataset.csv")
kl_house

#dataset is sourced from Kaggle: https://www.kaggle.com/datasets/dragonduck/property-listings-in-kuala-lumpur

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,"Built-up : 1,335 sq. ft.",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),"Built-up : 1,875 sq. ft.",Partly Furnished
3,"Cheras, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",4+1,3.0,2.0,Condominium (Corner),"Built-up : 1,513 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished
53881,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Unfurnished
53882,"Setapak, Kuala Lumpur","RM 540,000",4,2.0,3.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",Partly Furnished

In [33]:
kl_house.dtypes

Location          object
Price             object
Rooms             object
Bathrooms        float64
Car Parks        float64
Property Type     object
Size              object
Furnishing        object
dtype: object

In [34]:
kl_house.describe(include='all')

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
count,53883,53635,52177,51870.000000,36316.000000,53858,52820,46953
unique,112,4280,43,NaN,NaN,99,6190,4
top,"Mont Kiara, Kuala Lumpur","RM 1,200,000",3,NaN,NaN,Condominium,Land area : 22x75 sq. ft.,Partly Furnished
freq,5897,721,14249,NaN,NaN,11552,615,26605
mean,NaN,NaN,NaN,3.073434,2.007848,NaN,NaN,NaN
std,NaN,NaN,NaN,1.631079,1.310427,NaN,NaN,NaN
min,NaN,NaN,NaN,1.000000,1.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,2.000000,1.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,4.000000,2.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,20.000000,30.000000,NaN,NaN,NaN

Dealing with the missing data.

In [35]:
missing_values = kl_house.isnull()
missing_values.head(25)

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,False,False,False,False,False,False,False,False
1,False,False,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False
3,False,True,True,True,True,True,True,True
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,True,True,True,True,True,True,True
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,True,True,True,True,True,True,True
11,False,False,False,False,True,False,False,False
12,False,False,False,False,True,False,False,False
13,False,False,False,False,False,False,False,False
14,False,True,True,True,True,True,True,True
15,False,False,False,False,True,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,True,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,True,False,False,False
24,False,False,False,False,False,False,False,False

In [36]:
for column in missing_values.columns.values.tolist():
    print (column)
    print (missing_values[column].value_counts())
    print ('')

Location
False    53883
Name: Location, dtype: int64

Price
False    53635
True       248
Name: Price, dtype: int64

Rooms
False    52177
True      1706
Name: Rooms, dtype: int64

Bathrooms
False    51870
True      2013
Name: Bathrooms, dtype: int64

Car Parks
False    36316
True     17567
Name: Car Parks, dtype: int64

Property Type
False    53858
True        25
Name: Property Type, dtype: int64

Size
False    52820
True      1063
Name: Size, dtype: int64

Furnishing
False    46953
True      6930
Name: Furnishing, dtype: int64

In [37]:
nan_rows  = kl_house[kl_house.isna().any(axis=1)]
nan_rows

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
3,"Cheras, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,"Seputeh, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Ampang Hilir, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,680,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22 x 80 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53877,"Mont Kiara, Kuala Lumpur","RM 6,500,000",5+1,6.0,NaN,Bungalow (Corner),Land area : 6500 sq. ft.,Partly Furnished
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished
53881,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Unfurnished

In [42]:
all_nan = kl_house.dropna( how='all', subset=['Price', 'Rooms', 'Bathrooms', 'Car Parks', 'Property Type', 'Size', 'Furnishing'])
all_nan

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,"Built-up : 1,335 sq. ft.",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),"Built-up : 1,875 sq. ft.",Partly Furnished
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",4+1,3.0,2.0,Condominium (Corner),"Built-up : 1,513 sq. ft.",Partly Furnished
5,"Taman Tun Dr Ismail, Kuala Lumpur","RM 5,350,000",4+2,5.0,4.0,Bungalow,Land area : 7200 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished
53881,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Unfurnished
53882,"Setapak, Kuala Lumpur","RM 540,000",4,2.0,3.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",Partly Furnished

* Original dataset 53883 rows Ã— 8 columns.
* Dataset where all rows with all missing values in each column 53858 rows Ã— 8 columns.
* Total rows dropped 25

My strategy: Group all the data based on their location. This way it has higher accuracy when replacing the missing values.

In [197]:
#KLCC cluster

klcc = all_nan[all_nan['Location'].str.contains('KLCC|Klcc') == True]
klcc

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,"Built-up : 1,335 sq. ft.",Fully Furnished
35,"KLCC, Kuala Lumpur","RM 2,400,000",2,2.0,1.0,Serviced Residence,"Built-up : 1,006 sq. ft.",Fully Furnished
41,"KLCC, Kuala Lumpur","RM 3,600,000",4,4.0,NaN,Serviced Residence (Corner),"Built-up : 3,897 sq. ft.",Partly Furnished
42,"KLCC, Kuala Lumpur","RM 4,280,000",3+1,4.0,2.0,Serviced Residence (Corner),"Built-up : 2,195 sq. ft.",Fully Furnished
43,"KLCC, Kuala Lumpur","RM 2,300,000",1,2.0,1.0,Serviced Residence,"Built-up : 1,023 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53691,"KLCC, Kuala Lumpur","RM 780,000",2,1.0,NaN,Serviced Residence (Intermediate),Built-up : 980 sq. ft.,Fully Furnished
53707,"KLCC, Kuala Lumpur","RM 1,098,000",3,3.0,2.0,Serviced Residence (Intermediate),Land area : 1313 sq. ft.,Partly Furnished
53754,"KLCC, Kuala Lumpur","RM 5,200,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 12163 sq. ft.,Unfurnished
53801,"KLCC, Kuala Lumpur","RM 2,700,000",3+1,3.0,NaN,Serviced Residence,"Built-up : 1,819 sq. ft.",Partly Furnished
53863,"KLCC, Kuala Lumpur","RM 2,130,000",3+1,5.0,NaN,Serviced Residence,"Built-up : 2,474 sq. ft.",Partly Furnished

In [151]:
#Damansara Heights cluster

dh = all_nan[all_nan['Location'].str.contains('Damansara Heights')]
dh

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
17,"Damansara Heights, Kuala Lumpur","RM 4,500,000",5+1,7.0,NaN,Bungalow (Corner),"Built-up : 4,842 sq. ft.",Partly Furnished
21,"Damansara Heights, Kuala Lumpur","RM 1,550,000",1,1.0,1.0,Serviced Residence (Intermediate),Built-up : 904 sq. ft.,Fully Furnished
44,"Damansara Heights, Kuala Lumpur","RM 4,200,000",6,5.0,5.0,Bungalow,Land area : 5274 sq. ft.,Partly Furnished
107,"Damansara Heights, Kuala Lumpur","RM 6,800,000",5+2,7.0,NaN,Bungalow,Land area : 7000 sq. ft.,NaN
...,...,...,...,...,...,...,...,...
53721,"Damansara Heights, Kuala Lumpur","RM 6,670,888",5+1,6.0,NaN,Semi-detached House (EndLot),Land area : 24x85 sq. ft.,Partly Furnished
53722,"Damansara Heights, Kuala Lumpur","RM 5,231,888",5+1,6.0,NaN,Semi-detached House (Intermediate),Land area : 20x85 sq. ft.,Partly Furnished
53728,"Damansara Heights, Kuala Lumpur","RM 3,980,000",4+2,6.0,NaN,Semi-detached House (Intermediate),Land area : 40x98 sq. ft.,Partly Furnished
53870,"Damansara Heights, Kuala Lumpur","RM 3,500,000",NaN,NaN,NaN,Bungalow,NaN,NaN
53871,"Damansara Heights, Kuala Lumpur","RM 1,230,000",NaN,NaN,NaN,Bungalow,NaN,NaN

In [152]:
test = dh[dh['Location'].str.contains('Country')]
test

Empty DataFrame
Columns: [Location, Price, Rooms, Bathrooms, Car Parks, Property Type, Size, Furnishing]
Index: []

In [81]:
#CH Damansara cluster

chd = all_nan[all_nan['Location'].str.contains('Country Heights Damansara')]
chd

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
141,"Country Heights Damansara, Kuala Lumpur","RM 9,500,000",6+1,7.0,6.0,Bungalow (Corner),Land area : 10000 sq. ft.,Partly Furnished
310,"Country Heights Damansara, Kuala Lumpur","RM 8,000,000",7,7.0,6.0,Bungalow (Corner),Land area : 10600 sq. ft.,Partly Furnished
859,"Country Heights Damansara, Kuala Lumpur","RM 11,800,000",7,8.0,6.0,Bungalow (Corner),Land area : 8622 sq. ft.,Fully Furnished
1839,"Country Heights Damansara, Kuala Lumpur","RM 5,878,950",NaN,NaN,NaN,Residential Land,Land area : 10689 sq. ft.,NaN
1840,"Country Heights Damansara, Kuala Lumpur","RM 11,800,000",7,8.0,4.0,Bungalow (Intermediate),Land area : 8622 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51097,"Country Heights Damansara, Kuala Lumpur","RM 11,586,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 21065 sq. ft.,Unfurnished
51770,"Country Heights Damansara, Kuala Lumpur","RM 1,680,000",NaN,NaN,NaN,Residential Land,Land area : 8400 sq. ft.,NaN
51771,"Country Heights Damansara, Kuala Lumpur","RM 2,000,000",NaN,NaN,NaN,Residential Land,Land area : 10000 sq. ft.,NaN
51773,"Country Heights Damansara, Kuala Lumpur","RM 2,280,000",NaN,NaN,NaN,Residential Land,Land area : 11400 sq. ft.,NaN
53300,"Country Heights Damansara, Kuala Lumpur","RM 10,800,000",6+,8.0,4.0,Bungalow (Intermediate),Land area : 15250 sq. ft.,Fully Furnished

In [52]:
#Dutamas cluster

dutamas = all_nan[all_nan['Location'].str.contains('Dutamas')]
dutamas

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),"Built-up : 1,875 sq. ft.",Partly Furnished
28,"Dutamas, Kuala Lumpur","RM 1,035,880",3+1,4.0,1.0,Condominium (EndLot),"Built-up : 1,876 sq. ft.",Partly Furnished
101,"Dutamas, Kuala Lumpur","RM 1,180,000",3+1,4.0,1.0,Condominium (Intermediate),"Built-up : 1,942 sq. ft.",Partly Furnished
133,"Dutamas, Kuala Lumpur","RM 1,035,000",3+1,5.0,2.0,Condominium,"Built-up : 1,853 sq. ft.",Unknown
864,"Dutamas, Kuala Lumpur","RM 1,150,000",2,2.0,1.0,Serviced Residence,"Built-up : 1,148 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53765,"Dutamas, Kuala Lumpur","RM 1,020,000",3+1,3.0,NaN,Condominium,"Built-up : 1,799 sq. ft.",Partly Furnished
53766,"Dutamas, Kuala Lumpur","RM 1,080,000",3+1,3.0,NaN,Condominium,"Built-up : 1,451 sq. ft.",Partly Furnished
53775,"Dutamas, Kuala Lumpur","RM 620,000",3,3.0,2.0,Condominium (Corner),"Built-up : 1,614 sq. ft.",Fully Furnished
53776,"Dutamas, Kuala Lumpur","RM 500,000",3+1,3.0,2.0,Condominium (Intermediate),"Built-up : 1,432 sq. ft.",Partly Furnished
53808,"Dutamas, Kuala Lumpur","RM 1,500,000",6,6.0,3.0,Condominium,"Built-up : 3,300 sq. ft.",Fully Furnished

In [53]:
#Bukit Jalil cluster

jalil = all_nan[all_nan['Location'].str.contains('Bukit Jalil')]
jalil

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",4+1,3.0,2.0,Condominium (Corner),"Built-up : 1,513 sq. ft.",Partly Furnished
26,"Bukit Jalil, Kuala Lumpur","RM 610,000",3+1,2.0,2.0,Condominium (Intermediate),"Built-up : 1,236 sq. ft.",Partly Furnished
49,"Bukit Jalil, Kuala Lumpur","RM 1,070,000",4+1,4.0,4.0,Condominium (EndLot),"Built-up : 1,772 sq. ft.",Partly Furnished
50,"Bukit Jalil, Kuala Lumpur","RM 930,000",4,3.0,2.0,Condominium (EndLot),"Built-up : 1,513 sq. ft.",Partly Furnished
91,"Bukit Jalil, Kuala Lumpur","RM 620,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,232 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53606,"Bukit Jalil, Kuala Lumpur","RM 530,000",3+1,2.0,2.0,Condominium,"Built-up : 1,080 sq. ft.",Partly Furnished
53662,"Bukit Jalil, Kuala Lumpur","RM 1,050,000",3,3.0,2.0,Condominium (Corner),"Built-up : 1,301 sq. m.",Partly Furnished
53676,"Bukit Jalil, Kuala Lumpur","RM 1,350,000",5+1,6.0,2.0,3-sty Terrace/Link House (EndLot),Land area : 22x75 sq. ft.,Partly Furnished
53685,"Bukit Jalil, Kuala Lumpur","RM 1,500,000",6+1,6.0,6.0,3-sty Terrace/Link House,Land area : 22x100 sq. ft.,NaN
53740,"Bukit Jalil, Kuala Lumpur","RM 570,000",2,2.0,2.0,Condominium (Intermediate),Land area : 1032 sq. ft.,Unfurnished

In [54]:
#TTDI cluster

ttdi = all_nan[all_nan['Location'].str.contains('Taman Tun Dr Ismail')]
ttdi

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
5,"Taman Tun Dr Ismail, Kuala Lumpur","RM 5,350,000",4+2,5.0,4.0,Bungalow,Land area : 7200 sq. ft.,Partly Furnished
7,"Taman Tun Dr Ismail, Kuala Lumpur","RM 2,600,000",5,4.0,4.0,Semi-detached House,Land area : 3600 sq. ft.,Partly Furnished
8,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,950,000",4+1,4.0,3.0,2-sty Terrace/Link House (EndLot),Land area : 25x75 sq. ft.,Partly Furnished
11,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,680,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22 x 80 sq. ft.,Partly Furnished
12,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,700,000",3+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1900 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53471,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,000,000",1,1.0,1.0,Serviced Residence (Corner),Built-up : 840 sq. ft.,Partly Furnished
53473,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,790,000",4,3.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 24x75 sq. ft.,Partly Furnished
53570,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,780,000",3+1,5.0,NaN,Serviced Residence,"Built-up : 2,278 sq. ft.",Partly Furnished
53581,"Taman Tun Dr Ismail, Kuala Lumpur","RM 849,999",3,3.0,1.0,Townhouse (Duplex),Land area : 1345 sq. ft.,Partly Furnished
53667,"Taman Tun Dr Ismail, Kuala Lumpur","RM 1,199,000",4+1,3.0,NaN,1-sty Terrace/Link House (Intermediate),Land area : 2000 sq. ft.,NaN

In [55]:
#Cheras cluster

cheras = all_nan[all_nan['Location'].str.contains('Cheras')]
cheras

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
175,"Cheras, Kuala Lumpur","RM 820,000",NaN,4.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 22x80 sq. ft.,Unfurnished
290,"Cheras, Kuala Lumpur","RM 780,000",4+1,4.0,NaN,Bungalow (Corner),Land area : 5320 sq. ft.,NaN
386,"Cheras, Kuala Lumpur","RM 439,600",3,2.0,2.0,Condominium (Intermediate),Land area : 850sf~1000sf sq. ft.,Partly Furnished
392,"Cheras, Kuala Lumpur","RM 439,600",3,2.0,2.0,Condominium,Land area : 850-1000 sq. ft.,Partly Furnished
483,"Cheras, Kuala Lumpur","RM 868,000",5,4.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 23x75 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53665,"Cheras, Kuala Lumpur","RM 725,000",3,2.0,2.0,Condominium (Intermediate),"Built-up : 1,117 sq. ft.",Partly Furnished
53684,"Cheras, Kuala Lumpur","RM 1,300,000",5+1,5.0,NaN,Semi-detached House (Intermediate),Land area : 43x79 sq. ft.,Partly Furnished
53695,"Cheras, Kuala Lumpur","RM 1,100,000",4+1,4.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
53802,"Cheras, Kuala Lumpur","RM 568,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 20x65 sq. ft.,Partly Furnished
53803,"Cheras, Kuala Lumpur","RM 668,000",5,4.0,NaN,2-sty Terrace/Link House,Land area : 1300 sq. ft.,Partly Furnished

In [58]:
#Seputeh cluster

seputeh = all_nan[all_nan['Location'].str.contains('Seputeh')]
seputeh

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
463,"Seputeh, Kuala Lumpur","RM 5,500,000",5+1,6.0,4.0,Bungalow (Intermediate),Land area : 5446 sq. ft.,Fully Furnished
920,"Seputeh, Kuala Lumpur","RM 543,353",1,1.0,1.0,Condominium (Corner),Built-up : 667 sq. ft.,Partly Furnished
1280,"Seputeh, Kuala Lumpur","RM 1,290,000",5,4.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 20x78 sq. ft.,Partly Furnished
1772,"Seputeh, Kuala Lumpur","RM 650,000",2,2.0,1.0,Condominium (Intermediate),"Built-up : 1,067 sq. ft.",Fully Furnished
1800,"Seputeh, Kuala Lumpur","RM 620,000",3,2.0,1.0,Condominium,"Built-up : 1,290 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53744,"Seputeh, Kuala Lumpur","RM 6,000,000",5+1,5.0,2.0,Bungalow (Intermediate),Land area : 4850 sq. ft.,Partly Furnished
53745,"Seputeh, Kuala Lumpur","RM 5,300,000",6+1,5.0,2.0,Bungalow (Intermediate),Land area : 4844 sq. ft.,Partly Furnished
53746,"Seputeh, Kuala Lumpur","RM 3,080,000",5,5.0,NaN,Semi-detached House (Intermediate),Land area : 3200 sq. ft.,Partly Furnished
53861,"Seputeh, Kuala Lumpur","RM 4,100,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 10250 sq. ft.,NaN
53862,"Seputeh, Kuala Lumpur","RM 750,000",3,2.0,1.0,Condominium,Built-up : 915 sq. ft.,Partly Furnished

In [59]:
#Sri Petaling cluster

sp = all_nan[all_nan['Location'].str.contains('Sri Petaling')]
sp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
9,"Sri Petaling, Kuala Lumpur","RM 385,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 904 sq. ft.,Partly Furnished
439,"Sri Petaling, Kuala Lumpur","RM 950,000",4+1,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 1650 sq. ft.,Partly Furnished
737,"Sri Petaling, Kuala Lumpur","RM 2,400,000",5,5.0,6.0,Semi-detached House (Intermediate),Land area : 4000 sq. ft.,Partly Furnished
1188,"Sri Petaling, Kuala Lumpur","RM 1,600,000",5+1,4.0,4.0,2-sty Terrace/Link House (Corner),Land area : 4300 sq. ft.,Partly Furnished
1284,"Sri Petaling, Kuala Lumpur","RM 638,000",3+1,3.0,1.0,Serviced Residence,"Built-up : 1,278 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53739,"Sri Petaling, Kuala Lumpur","RM 1,650,000",6+1,7.0,4.0,Semi-detached House,Land area : 2800 sq. ft.,NaN
53748,"Sri Petaling, Kuala Lumpur","RM 500,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,300 sq. ft.",Partly Furnished
53778,"Sri Petaling, Kuala Lumpur","RM 1,880,000",4,4.0,NaN,Semi-detached House (Intermediate),Land area : 4000 sq. ft.,Partly Furnished
53826,"Sri Petaling, Kuala Lumpur","RM 1,800,000",4+1,5.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 22 x 85 sq. ft.,Fully Furnished
53850,"Sri Petaling, Kuala Lumpur","RM 1,400,000",3+1,5.0,NaN,Condominium,"Built-up : 2,024 sq. ft.",Fully Furnished

In [60]:
#Ampang Hilir cluster

ah = all_nan[all_nan['Location'].str.contains('Ampang Hilir')]
ah

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
31,"Ampang Hilir, Kuala Lumpur","RM 3,300,000",4+1,4.0,4.0,Condominium,"Built-up : 3,536 sq. ft.",Unfurnished
33,"Ampang Hilir, Kuala Lumpur","RM 460,000",1,1.0,1.0,Serviced Residence,Built-up : 613 sq. ft.,Fully Furnished
60,"Ampang Hilir, Kuala Lumpur","RM 4,800,000",5,6.0,3.0,Condominium,"Built-up : 4,300 sq. ft.",Partly Furnished
61,"Ampang Hilir, Kuala Lumpur","RM 3,780,000",4+1,5.0,4.0,Condominium (Corner),"Built-up : 3,628 sq. ft.",Partly Furnished
223,"Ampang Hilir, Kuala Lumpur","RM 3,710,000",4+1,5.0,NaN,Condominium,"Built-up : 3,369 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53424,"Ampang Hilir, Kuala Lumpur","RM 1,900,000",4,3.0,NaN,Condominium,Land area : 2034 sq. ft.,Unfurnished
53525,"Ampang Hilir, Kuala Lumpur","RM 49,590,000",NaN,NaN,NaN,Residential Land,Land area : 7 acres,NaN
53677,"Ampang Hilir, Kuala Lumpur","RM 650,000",2,2.0,NaN,Serviced Residence (Corner),Built-up : 950 sq. ft.,Fully Furnished
53788,"Ampang Hilir, Kuala Lumpur","RM 4,200,000",4+1,6.0,NaN,Condominium,"Built-up : 3,240 sq. ft.",Unfurnished
53792,"Ampang Hilir, Kuala Lumpur","RM 530,000",1,1.0,1.0,Serviced Residence (Corner),Built-up : 501 sq. ft.,Fully Furnished

In [61]:
#Bukit Tunku cluster

bt = all_nan[all_nan['Location'].str.contains('Bukit Tunku')]
bt

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
16,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 9,000,000",6+1,7.0,4.0,Bungalow (Corner),Land area : 8500 sq. ft.,Partly Furnished
434,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 6,900,000",4+2,5.0,NaN,Bungalow,Land area : 12000 sq. ft.,Partly Furnished
465,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 14,800,000",7+1,9.0,6.0,Bungalow (Corner),Land area : 12000 sq. ft.,Partly Furnished
652,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 5,500,000",5,6.0,5.0,Condominium (Penthouse),"Built-up : 6,900 sq. ft.",Partly Furnished
791,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 14,800,000",7+1,8.0,6.0,Bungalow (Corner),Land area : 12000 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
52677,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 3,000,000",3+1,5.0,NaN,Condominium,"Built-up : 2,996 sq. ft.",Partly Furnished
52678,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 3,050,000",3+1,5.0,NaN,Condominium,"Built-up : 2,996 sq. ft.",Partly Furnished
52783,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 15,000,000",7+1,8.0,6.0,Bungalow,Land area : 19700 sq. ft.,NaN
53053,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 1,300,000",2,3.0,2.0,Condominium,"Built-up : 1,730 sq. ft.",Fully Furnished
53845,"Bukit Tunku (Kenny Hills), Kuala Lumpur","RM 4,950,000",4+1,5.0,NaN,Semi-detached House (Intermediate),Land area : 3600 sq. ft.,Partly Furnished

In [62]:
#Mt Kiara cluster

mk = all_nan[all_nan['Location'].str.contains('Kiara')]
mk

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
18,"Mont Kiara, Kuala Lumpur","RM 1,780,000",4+1,4.0,2.0,Condominium (Corner),"Built-up : 1,830 sq. ft.",Partly Furnished
19,"Mont Kiara, Kuala Lumpur","RM 3,450,000",4+1,6.0,3.0,Condominium (Corner),"Built-up : 3,720 sq. ft.",Fully Furnished
22,"Mont Kiara, Kuala Lumpur","RM 1,500,000",3+1,4.0,3.0,Condominium,"Built-up : 2,163 sq. ft.",Fully Furnished
23,"Mont Kiara, Kuala Lumpur","RM 1,450,000",3+1,4.0,NaN,Condominium,"Built-up : 2,163 sq. ft.",Fully Furnished
29,"Mont Kiara, Kuala Lumpur","RM 1,830,000",3,4.0,NaN,Condominium (Intermediate),"Built-up : 1,668 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53796,"Mont Kiara, Kuala Lumpur","RM 720,000",4,3.0,3.0,2-sty Terrace/Link House (Corner),"Built-up : 1,200 sq. ft.",Partly Furnished
53810,"Mont Kiara, Kuala Lumpur","RM 830,000",3,2.0,2.0,Condominium,"Built-up : 1,280 sq. ft.",Fully Furnished
53846,"Mont Kiara, Kuala Lumpur","RM 800,000",3+1,3.0,NaN,Condominium,"Built-up : 1,550 sq. ft.",NaN
53865,"Mont Kiara, Kuala Lumpur","RM 2,480,000",5+1,4.0,NaN,2.5-sty Terrace/Link House (EndLot),Land area : 2195 sq. ft.,Partly Furnished
53877,"Mont Kiara, Kuala Lumpur","RM 6,500,000",5+1,6.0,NaN,Bungalow (Corner),Land area : 6500 sq. ft.,Partly Furnished

In [64]:
#Desa ParkCity cluster

dp = all_nan[all_nan['Location'].str.contains('Desa ParkCity')]
dp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
20,"Desa ParkCity, Kuala Lumpur","RM 1,500,000",3+2,4.0,2.0,Condominium (Corner),"Built-up : 1,798 sq. ft.",Partly Furnished
113,"Desa ParkCity, Kuala Lumpur","RM 2,850,000",3+1,3.0,NaN,3-sty Terrace/Link House (Intermediate),"Built-up : 3,211 sq. ft.",Partly Furnished
114,"Desa ParkCity, Kuala Lumpur","RM 1,050,000",2+1,2.0,2.0,Condominium,"Built-up : 1,389 sq. ft.",Partly Furnished
132,"Desa ParkCity, Kuala Lumpur","RM 1,980,000",3+1,4.0,NaN,2-sty Terrace/Link House,"Built-up : 2,200 sq. ft.",Partly Furnished
145,"Desa ParkCity, Kuala Lumpur","RM 3,490,000",5,5.0,NaN,3-sty Terrace/Link House (Corner),Land area : 38x75 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53758,"Desa ParkCity, Kuala Lumpur","RM 520,000",3,2.0,2.0,2-sty Terrace/Link House,Built-up : 829 sq. ft.,Partly Furnished
53760,"Desa ParkCity, Kuala Lumpur","RM 1,930,000",5+1,7.0,2.0,3-sty Terrace/Link House,"Built-up : 2,400 sq. ft.",Partly Furnished
53795,"Desa ParkCity, Kuala Lumpur","RM 720,000",3,2.0,2.0,2-sty Terrace/Link House,"Built-up : 1,206 sq. ft.",Partly Furnished
53800,"Desa ParkCity, Kuala Lumpur","RM 1,380,000",3+1,4.0,2.0,Townhouse (EndLot),"Built-up : 2,551 sq. ft.",Partly Furnished
53857,"Desa ParkCity, Kuala Lumpur","RM 1,600,000",3+1,3.0,2.0,3-sty Terrace/Link House (Intermediate),"Built-up : 1,900 sq. ft.",Partly Furnished

In [65]:
#Bangsar South cluster

bs = all_nan[all_nan['Location'].str.contains('Bangsar South')]
bs

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
24,"Bangsar South, Kuala Lumpur","RM 490,000",1,1.0,1.0,Serviced Residence,Built-up : 520 sq. ft.,Fully Furnished
52,"Bangsar South, Kuala Lumpur","RM 780,000",2,2.0,1.0,Serviced Residence (Corner),Built-up : 880 sq. ft.,Partly Furnished
63,"Bangsar South, Kuala Lumpur","RM 850,000",2+1,2.0,1.0,Serviced Residence,"Built-up : 1,050 sq. ft.",Fully Furnished
116,"Bangsar South, Kuala Lumpur","RM 630,000",1+1,1.0,1.0,Serviced Residence,Built-up : 663 sq. ft.,Partly Furnished
127,"Bangsar South, Kuala Lumpur","RM 630,000",1+1,1.0,1.0,Serviced Residence,Built-up : 650 sq. ft.,Fully Furnished
...,...,...,...,...,...,...,...,...
53412,"Bangsar South, Kuala Lumpur","RM 435,000",1+1,1.0,1.0,Serviced Residence,Built-up : 500 sq. ft.,NaN
53455,"Bangsar South, Kuala Lumpur","RM 350,000",2,1.0,1.0,Apartment,Built-up : 500 sq. ft.,Partly Furnished
53457,"Bangsar South, Kuala Lumpur","RM 500,000",2,1.0,1.0,Apartment,Built-up : 635 sq. ft.,Partly Furnished
53580,"Bangsar South, Kuala Lumpur","RM 570,000",1+1,1.0,NaN,Serviced Residence,Built-up : 648 sq. ft.,NaN
53724,"Bangsar South, Kuala Lumpur","RM 1,355,000",3+1,3.0,NaN,Serviced Residence (Corner),"Built-up : 1,399 sq. ft.",Partly Furnished

In [66]:
#Sg Besi cluster

sb = all_nan[all_nan['Location'].str.contains('Sungai Besi')]
sb

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
25,"Sungai Besi, Kuala Lumpur",NaN,5,4.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 20x75 sq. ft.,Fully Furnished
45,"Sungai Besi, Kuala Lumpur","RM 900,000",6,5.0,3.0,3-sty Terrace/Link House (Intermediate),Land area : 20 X 80 sq. ft.,Fully Furnished
66,"Sungai Besi, Kuala Lumpur","RM 999,000",4+1,4.0,2.0,3-sty Terrace/Link House (Intermediate),"Built-up : 2,512 sq. ft.",Partly Furnished
136,"Sungai Besi, Kuala Lumpur","RM 448,800",3,3.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,045 sq. ft.",Unfurnished
361,"Sungai Besi, Kuala Lumpur","RM 1,340,000",4+1,6.0,4.0,3-sty Terrace/Link House (Intermediate),Land area : 24x80 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53753,"Sungai Besi, Kuala Lumpur","RM 1,450,000",5,4.0,NaN,3-sty Terrace/Link House (EndLot),Land area : 10+ 20x80 sq. ft.,Partly Furnished
53767,"Sungai Besi, Kuala Lumpur","RM 1,450,000",4+1,5.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 24x80 sq. ft.,Partly Furnished
53768,"Sungai Besi, Kuala Lumpur","RM 1,400,000",4,3.0,NaN,3-sty Terrace/Link House (Intermediate),"Built-up : 3,200 sq. ft.",Unfurnished
53770,"Sungai Besi, Kuala Lumpur","RM 2,350,000",5+1,5.0,NaN,3-sty Terrace/Link House (Corner),Land area : 6300 sq. ft.,Unfurnished
53832,"Sungai Besi, Kuala Lumpur","RM 680,000",2+1,2.0,2.0,Serviced Residence (Intermediate),"Built-up : 1,025 sq. ft.",Partly Furnished

In [67]:
#Old Klang Road cluster

ok = all_nan[all_nan['Location'].str.contains('Klang Lama')]
ok

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
39,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 1,438,000",3+2,4.0,3.0,Condominium (Corner),"Built-up : 2,378 sq. ft.",Partly Furnished
160,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 509,000",2,2.0,1.0,Serviced Residence,Built-up : 797 sq. ft.,NaN
261,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 655,000",3+1,2.0,2.0,Serviced Residence (Corner),"Built-up : 1,094 sq. ft.",Partly Furnished
331,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 350,000",3,2.0,1.0,Serviced Residence,Built-up : 950 sq. ft.,Partly Furnished
346,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 530,000",3+1,2.0,1.0,Serviced Residence (Corner),Built-up : 900 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53638,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 335,000",3,2.0,1.0,Serviced Residence (Intermediate),Built-up : 950 sq. ft.,Partly Furnished
53663,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 700,000",3+1,2.0,1.0,Condominium (Penthouse),Land area : 900 sq. ft.,Partly Furnished
53784,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 738,000",2,2.0,2.0,Serviced Residence (Corner),Land area : 1399 sq. ft.,Partly Furnished
53816,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 520,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,130 sq. ft.",Partly Furnished
53875,"Jalan Klang Lama (Old Klang Road), Kuala Lumpur","RM 475,000",3,2.0,NaN,Serviced Residence (Intermediate),Built-up : 852 sq. ft.,Partly Furnished

In [227]:
#Kepong cluster

kepong = all_nan[all_nan['Location'].str.contains('Kepong|kepong') == True]
kepong

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
32,"Kepong, Kuala Lumpur","RM 560,000",3,2.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 16x55 sq. ft.,Partly Furnished
111,"Kepong, Kuala Lumpur","RM 2,040,000",5+1,5.0,4.0,2.5-sty Terrace/Link House (Intermediate),Land area : 32 x 75 sq. ft.,Partly Furnished
169,"Kepong, Kuala Lumpur","RM 920,000",5,3.0,NaN,2-sty Terrace/Link House (EndLot),Land area : 20 x 80 sq. ft.,Partly Furnished
206,"Kepong, Kuala Lumpur","RM 638,000",3+1,2.0,4.0,1.5-sty Terrace/Link House (EndLot),Land area : 27x70 sq. ft.,Partly Furnished
208,"Kepong, Kuala Lumpur","RM 850,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x80 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53814,"Kepong, Kuala Lumpur","RM 599,000",3,2.0,1.0,2-sty Terrace/Link House (Intermediate),Built-up : 880 sq. ft.,Partly Furnished
53823,"Kepong, Kuala Lumpur","RM 2,650,000",4+1,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 45x75 sq. ft.,NaN
53847,"Kepong, Kuala Lumpur","RM 555,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 16x55 sq. ft.,Partly Furnished
53849,"Kepong, Kuala Lumpur","RM 3,150,000",5+1,6.0,NaN,Semi-detached House (Intermediate),Land area : 45x90 sq. ft.,Partly Furnished
53873,"Kepong, Kuala Lumpur","RM 499,000",3,2.0,NaN,1-sty Terrace/Link House (Intermediate),Land area : 22x65 sq. ft.,Unfurnished

In [69]:
#Jalan Kuching cluster

jk = all_nan[all_nan['Location'].str.contains('Kuching')]
jk

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
394,"Jalan Kuching, Kuala Lumpur","RM 580,000",3,2.0,1.0,Condominium (Corner),"Built-up : 1,590 sq. ft.",Partly Furnished
1146,"Jalan Kuching, Kuala Lumpur","RM 380,000",3,2.0,1.0,Apartment (Intermediate),"Built-up : 1,216 sq. ft.",Partly Furnished
1741,"Jalan Kuching, Kuala Lumpur","RM 750,000",3+1,2.0,2.0,Condominium,"Built-up : 1,590 sq. ft.",Partly Furnished
1869,"Jalan Kuching, Kuala Lumpur","RM 400,000",3,2.0,1.0,Condominium,"Built-up : 1,100 sq. ft.",Partly Furnished
1937,"Jalan Kuching, Kuala Lumpur","RM 580,000",3,2.0,NaN,Condominium,"Built-up : 1,295 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53064,"Jalan Kuching, Kuala Lumpur","RM 2,800,000",5+1,6.0,NaN,Semi-detached House (Corner),Land area : 5851 sq. ft.,Unfurnished
53103,"Jalan Kuching, Kuala Lumpur","RM 620,000",3,2.0,1.0,Condominium,"Built-up : 1,015 sq. ft.",Partly Furnished
53133,"Jalan Kuching, Kuala Lumpur","RM 576,670",3,2.0,2.0,Serviced Residence (Corner),"Built-up : 1,018 sq. ft.",NaN
53160,"Jalan Kuching, Kuala Lumpur","RM 630,000",3,2.0,1.0,Condominium,"Built-up : 1,018 sq. ft.",Fully Furnished
53712,"Jalan Kuching, Kuala Lumpur","RM 460,000",3,2.0,1.0,Condominium (Intermediate),"Built-up : 1,050 sq. ft.",Fully Furnished

In [225]:
#Taman Melawati cluster

tm = all_nan[all_nan['Location'].str.contains('Melawati|Casa Rimba') == True]
tm

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
58,"Taman Melawati, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,"Taman Melawati, Kuala Lumpur","RM 750,000",4,3.0,3.0,2-sty Terrace/Link House,Land area : 24 X 75 sq. ft.,Partly Furnished
338,"Taman Melawati, Kuala Lumpur","RM 2,800,000",4+1,6.0,4.0,Bungalow (Corner),Land area : 5628 sq. ft.,Partly Furnished
521,"Taman Melawati, Kuala Lumpur","RM 2,000,000",6,6.0,3.0,Semi-detached House (Intermediate),Land area : 3200 sq. ft.,Partly Furnished
1159,"Taman Melawati, Kuala Lumpur","RM 1,200,000",4,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 38x70 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53742,"Taman Melawati, Kuala Lumpur","RM 600,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 18x65 sq. ft.,Partly Furnished
53806,"Taman Melawati, Kuala Lumpur","RM 3,500,000",5+1,5.0,NaN,Bungalow (Intermediate),Land area : 4973 sq. ft.,Partly Furnished
53852,"Taman Melawati, Kuala Lumpur","RM 1,250,000",6,7.0,NaN,3-sty Terrace/Link House,Land area : 22 x 75 sq. ft.,Unfurnished
53853,"Taman Melawati, Kuala Lumpur","RM 1,500,000",4+1,5.0,3.0,Townhouse (Intermediate),Land area : 32 x 85 sq. ft.,Partly Furnished
53855,"Taman Melawati, Kuala Lumpur","RM 2,100,000",5,5.0,2.0,3-sty Terrace/Link House (Intermediate),Land area : 2132 sq. ft.,Unfurnished

In [72]:
#Sentul cluster

sentul = all_nan[all_nan['Location'].str.contains('Sentul')]
sentul

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
158,"Sentul, Kuala Lumpur","RM 668,000",3+1,3.0,3.0,Condominium (Corner),"Built-up : 1,345 sq. ft.",Fully Furnished
174,"Sentul, Kuala Lumpur","RM 670,000",3,2.0,2.0,Condominium,"Built-up : 1,085 sq. ft.",Partly Furnished
205,"Sentul, Kuala Lumpur","RM 900,000",3+1,4.0,3.0,Condominium,"Built-up : 1,381 sq. ft.",NaN
227,"Sentul, Kuala Lumpur","RM 960,000",3+1,4.0,2.0,Condominium (Corner),"Built-up : 1,488 sq. ft.",Unfurnished
365,"Sentul, Kuala Lumpur","RM 320,000",4,2.0,2.0,Serviced Residence (Corner),Land area : 646sf~1001sf sq. ft.,Unfurnished
...,...,...,...,...,...,...,...,...
53598,"Sentul, Kuala Lumpur","RM 950,000",3,3.0,NaN,Condominium (Intermediate),"Built-up : 1,488 sq. ft.",Partly Furnished
53600,"Sentul, Kuala Lumpur","RM 1,100,000",3,3.0,2.0,Condominium,"Built-up : 1,544 sq. ft.",Partly Furnished
53601,"Sentul, Kuala Lumpur","RM 1,050,000",3,3.0,2.0,Condominium,"Built-up : 1,488 sq. ft.",Partly Furnished
53714,"Sentul, Kuala Lumpur","RM 675,000",2,2.0,1.0,Condominium (Intermediate),Built-up : 820 sq. ft.,Unfurnished
53783,"Sentul, Kuala Lumpur","RM 1,100,000",3+2,3.0,3.0,Condominium (Corner),"Built-up : 2,250 sq. ft.",Partly Furnished

In [73]:
#KL Sentral cluster

kls = all_nan[all_nan['Location'].str.contains('Sentral')]
kls

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
67,"KL Sentral, Kuala Lumpur","RM 3,500,000",1,1.0,1.0,Serviced Residence,"Built-up : 1,648 sq. ft.",Partly Furnished
139,"KL Sentral, Kuala Lumpur","RM 2,716,000",3+1,4.0,2.0,Serviced Residence (Corner),"Built-up : 2,227 sq. ft.",Partly Furnished
140,"KL Sentral, Kuala Lumpur","RM 1,480,000",3+1,3.0,NaN,Condominium (Corner),"Built-up : 1,544 sq. ft.",Fully Furnished
383,"KL Sentral, Kuala Lumpur","RM 783,990",1,1.0,1.0,Serviced Residence,Built-up : 650 sq. ft.,Partly Furnished
412,"KL Sentral, Kuala Lumpur","RM 2,300,000",3+1,4.0,2.0,Serviced Residence,"Built-up : 1,873 sq. ft.",NaN
...,...,...,...,...,...,...,...,...
53762,"KL Sentral, Kuala Lumpur","RM 1,980,000",4+1,5.0,2.0,Condominium (Corner),"Built-up : 2,886 sq. ft.",Partly Furnished
53771,"KL Sentral, Kuala Lumpur","RM 1,500,000",3+1,3.0,2.0,Condominium,"Built-up : 1,584 sq. ft.",Fully Furnished
53798,"KL Sentral, Kuala Lumpur","RM 2,350,000",5,5.0,2.0,Condominium (Corner),"Built-up : 2,881 sq. ft.",Fully Furnished
53851,"KL Sentral, Kuala Lumpur","RM 2,200,000",4+1,4.0,NaN,Condominium,"Built-up : 2,900 sq. ft.",Fully Furnished
53868,"KL Sentral, Kuala Lumpur","RM 1,400,000",3+1,3.0,2.0,Condominium (Corner),Land area : 1544 sq. ft.,Fully Furnished

In [74]:
#Setapak cluster

setapak = all_nan[all_nan['Location'].str.contains('Setapak')]
setapak

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
72,"Setapak, Kuala Lumpur","RM 580,000",4+1,2.0,2.0,Condominium (Corner),"Built-up : 1,550 sq. ft.",Partly Furnished
194,"Setapak, Kuala Lumpur","RM 780,000",3,3.0,2.0,Condominium (Corner),"Built-up : 1,368 sq. ft.",Partly Furnished
242,"Setapak, Kuala Lumpur","RM 240,000",3,2.0,1.0,Condominium,Built-up : 850 sq. ft.,NaN
353,"Setapak, Kuala Lumpur","RM 380,000",3+1,2.0,2.0,Condominium,Built-up : 950 sq. ft.,Unfurnished
448,"Setapak, Kuala Lumpur","RM 428,000",3+1,2.0,2.0,Serviced Residence,Built-up : 918 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53804,"Setapak, Kuala Lumpur","RM 530,000",4,2.0,1.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",Partly Furnished
53811,"Setapak, Kuala Lumpur","RM 250,000",3,2.0,1.0,Condominium (Corner),Built-up : 845 sq. ft.,Partly Furnished
53813,"Setapak, Kuala Lumpur","RM 500,000",4,2.0,2.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",NaN
53815,"Setapak, Kuala Lumpur","RM 410,000",3,2.0,NaN,Condominium (Intermediate),Land area : 1100 sq. ft.,Partly Furnished
53882,"Setapak, Kuala Lumpur","RM 540,000",4,2.0,3.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",Partly Furnished

In [75]:
#Bangsar cluster

bangsar = all_nan[all_nan['Location'].str.contains('Bangsar')]
bangsar

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
24,"Bangsar South, Kuala Lumpur","RM 490,000",1,1.0,1.0,Serviced Residence,Built-up : 520 sq. ft.,Fully Furnished
52,"Bangsar South, Kuala Lumpur","RM 780,000",2,2.0,1.0,Serviced Residence (Corner),Built-up : 880 sq. ft.,Partly Furnished
63,"Bangsar South, Kuala Lumpur","RM 850,000",2+1,2.0,1.0,Serviced Residence,"Built-up : 1,050 sq. ft.",Fully Furnished
116,"Bangsar South, Kuala Lumpur","RM 630,000",1+1,1.0,1.0,Serviced Residence,Built-up : 663 sq. ft.,Partly Furnished
127,"Bangsar South, Kuala Lumpur","RM 630,000",1+1,1.0,1.0,Serviced Residence,Built-up : 650 sq. ft.,Fully Furnished
...,...,...,...,...,...,...,...,...
53724,"Bangsar South, Kuala Lumpur","RM 1,355,000",3+1,3.0,NaN,Serviced Residence (Corner),"Built-up : 1,399 sq. ft.",Partly Furnished
53727,"Bangsar, Kuala Lumpur","RM 2,300,000",5+1,6.0,NaN,Condominium (Corner),"Built-up : 3,500 sq. ft.",Partly Furnished
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished

In [76]:
#Bangsar cluster

bangsaronly = bangsar[~bangsar['Location'].str.contains('South')]
bangsaronly

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
211,"Bangsar, Kuala Lumpur","RM 3,800,000",4+1,5.0,4.0,Bungalow (Corner),"Built-up : 4,067 sq. ft.",Partly Furnished
281,"Bangsar, Kuala Lumpur","RM 1,530,000",3+1,3.0,2.0,Condominium (Corner),"Built-up : 2,095 sq. ft.",Fully Furnished
315,"Bangsar, Kuala Lumpur","RM 1,600,000",3,2.0,2.0,Townhouse,"Built-up : 2,400 sq. ft.",Partly Furnished
337,"Bangsar, Kuala Lumpur","RM 1,300,000",3,2.0,2.0,Townhouse (Intermediate),Land area : 24x55 sq. ft.,Partly Furnished
356,"Bangsar, Kuala Lumpur","RM 12,000,000",6+1,6.0,4.0,Bungalow,Land area : 11500 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53636,"Bangsar, Kuala Lumpur","RM 6,990,000",5+1,5.0,3.0,Bungalow (Corner),Land area : 9700 sq. ft.,Partly Furnished
53727,"Bangsar, Kuala Lumpur","RM 2,300,000",5+1,6.0,NaN,Condominium (Corner),"Built-up : 3,500 sq. ft.",Partly Furnished
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished

In [231]:
#City Centre, KL City cluster

cc = all_nan[all_nan['Location'].str.contains('City Centre|KL City') == True]
cc

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
55,"KL City, Kuala Lumpur","RM 1,800,000",2,2.0,1.0,Serviced Residence (Duplex),"Built-up : 1,244 sq. ft.",Fully Furnished
78,"KL City, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,"City Centre, Kuala Lumpur","RM 4,080,000",4+1,5.0,2.0,Condominium (Corner),"Built-up : 3,713 sq. ft.",Partly Furnished
104,"City Centre, Kuala Lumpur","RM 1,700,000",2+1,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,442 sq. ft.",Fully Furnished
218,"KL City, Kuala Lumpur","RM 1,207,000",Studio,1.0,1.0,Serviced Residence (Intermediate),Built-up : 685 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53558,"City Centre, Kuala Lumpur","RM 1,450,000",1,2.0,1.0,Serviced Residence (Corner),"Built-up : 1,131 sq. ft.",Partly Furnished
53565,"KL City, Kuala Lumpur","RM 1,200,000",2,2.0,NaN,Serviced Residence,Built-up : 651 sq. ft.,Fully Furnished
53641,"KL City, Kuala Lumpur","RM 1,280,000",2,2.0,1.0,Serviced Residence,Land area : 868 sq. ft.,Fully Furnished
53711,"KL City, Kuala Lumpur","RM 738,000",1,1.0,1.0,Serviced Residence (Corner),Land area : 732 sq. ft.,Fully Furnished
53769,"City Centre, Kuala Lumpur","RM 1,260,000",2,2.0,NaN,Condominium (Intermediate),"Built-up : 1,400 sq. ft.",Fully Furnished

In [78]:
#Bukit Bintang cluster

bb = all_nan[all_nan['Location'].str.contains('Bintang')]
bb

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
368,"Bukit Bintang, Kuala Lumpur","RM 6,000,000",4+1,5.0,2.0,Serviced Residence (Corner),"Built-up : 4,157 sq. ft.",Partly Furnished
580,"Bukit Bintang, Kuala Lumpur","RM 2,044,800",2,2.0,1.0,Serviced Residence,Built-up : 912 sq. ft.,Fully Furnished
639,"Bukit Bintang, Kuala Lumpur","RM 1,000,000",NaN,2.0,1.0,Serviced Residence,"Built-up : 1,012 sq. ft.",Fully Furnished
690,"Bukit Bintang, Kuala Lumpur","RM 900,000",3,3.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,063 sq. ft.",Fully Furnished
695,"Bukit Bintang, Kuala Lumpur","RM 2,981,550",2,3.0,NaN,Serviced Residence (Corner),"Built-up : 1,509 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53389,"Bukit Bintang, Kuala Lumpur","RM 910,000",1,1.0,1.0,Serviced Residence,NaN,Partly Furnished
53559,"Bukit Bintang, Kuala Lumpur","RM 1,600,000",3+1,3.0,2.0,Condominium (Corner),"Built-up : 1,822 sq. ft.",Partly Furnished
53561,"Bukit Bintang, Kuala Lumpur","RM 2,100,000",4,4.0,2.0,Condominium,"Built-up : 2,153 sq. ft.",Partly Furnished
53652,"Bukit Bintang, Kuala Lumpur","RM 530,000",Studio,1.0,1.0,Condominium,Built-up : 522 sq. ft.,Fully Furnished
53787,"Bukit Bintang, Kuala Lumpur","RM 2,550,000",2,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,307 sq. ft.",Fully Furnished

In [80]:
#Kuchai Lama cluster

kuchai = all_nan[all_nan['Location'].str.contains('Kuchai Lama')]
kuchai

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
739,"Kuchai Lama, Kuala Lumpur","RM 700,000",3+1,3.0,2.0,Condominium (Intermediate),"Built-up : 1,496 sq. ft.",Partly Furnished
1850,"Kuchai Lama, Kuala Lumpur","RM 390,000",3,2.0,1.0,Serviced Residence (Intermediate),Built-up : 935 sq. ft.,Partly Furnished
1870,"Kuchai Lama, Kuala Lumpur","RM 300,000",3,2.0,1.0,Condominium,Built-up : 905 sq. ft.,Partly Furnished
1955,"Kuchai Lama, Kuala Lumpur","RM 460,000",3,2.0,2.0,Serviced Residence (Intermediate),Built-up : 935 sq. ft.,Partly Furnished
2300,"Kuchai Lama, Kuala Lumpur","RM 838,000",5,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x70 sq. ft.,Unfurnished
...,...,...,...,...,...,...,...,...
53501,"Kuchai Lama, Kuala Lumpur","RM 700,000",3+1,3.0,2.0,Condominium (Corner),"Built-up : 1,474 sq. ft.",Unfurnished
53533,"Kuchai Lama, Kuala Lumpur","RM 530,000",3+1,2.0,2.0,Condominium,"Built-up : 1,313 sq. ft.",NaN
53539,"Kuchai Lama, Kuala Lumpur","RM 418,000",3,2.0,1.0,Serviced Residence,NaN,NaN
53859,"Kuchai Lama, Kuala Lumpur","RM 300,000",3,2.0,1.0,Serviced Residence (Intermediate),Built-up : 820 sq. ft.,Unfurnished
53864,"Kuchai Lama, Kuala Lumpur","RM 585,000",3+1,3.0,2.0,Condominium,"Built-up : 1,313 sq. ft.",NaN

In [85]:
#Taman Desa cluster

td = all_nan[all_nan['Location'].str.contains('Taman Desa')]
td

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
143,"Taman Desa, Kuala Lumpur","RM 500,000",2,2.0,1.0,Serviced Residence (Corner),Built-up : 715 sq. ft.,Partly Furnished
216,"Taman Desa, Kuala Lumpur","RM 530,000",2,2.0,NaN,Serviced Residence,Built-up : 715 sq. ft.,NaN
391,"Taman Desa, Kuala Lumpur","RM 1,480,000",3+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22&#8217;x100&#8217; sq. ft.,NaN
438,"Taman Desa, Kuala Lumpur","RM 3,690,000",4+1,5.0,6.0,Semi-detached House,Land area : 3658 sq. ft.,Unfurnished
444,"Taman Desa, Kuala Lumpur","RM 628,000",3,2.0,1.0,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53543,"Taman Desa, Kuala Lumpur","RM 480,000",2,2.0,1.0,Serviced Residence (Intermediate),Built-up : 715 sq. ft.,Partly Furnished
53544,"Taman Desa, Kuala Lumpur","RM 550,000",2,2.0,1.0,Serviced Residence (Intermediate),Built-up : 715 sq. ft.,Partly Furnished
53549,"Taman Desa, Kuala Lumpur","RM 350,000",3,2.0,1.0,Apartment (Intermediate),Land area : 953 sq. ft.,Fully Furnished
53550,"Taman Desa, Kuala Lumpur","RM 299,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 830 sq. ft.,Partly Furnished
53670,"Taman Desa, Kuala Lumpur","RM 1,100,000",4+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x80 sq. ft.,Partly Furnished

In [86]:
#Segambut cluster

sgmbt = all_nan[all_nan['Location'].str.contains('Segambut')]
sgmbt

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
215,"Segambut, Kuala Lumpur","RM 635,000",3+1,4.0,2.0,Condominium (Corner),"Built-up : 1,643 sq. ft.",Partly Furnished
475,"Segambut, Kuala Lumpur","RM 720,000",3+1,3.0,2.0,Condominium (Corner),"Built-up : 1,577 sq. ft.",Fully Furnished
672,"Segambut, Kuala Lumpur","RM 1,147,000",5+1,5.0,5.0,Condominium,"Built-up : 2,500 sq. ft.",Partly Furnished
1161,"Segambut, Kuala Lumpur","RM 330,000",2,2.0,NaN,2-sty Terrace/Link House,Land area : 14x43 sq. ft.,NaN
1194,"Segambut, Kuala Lumpur","RM 690,000",3+1,3.0,2.0,Condominium (Intermediate),Land area : 1298 sq. ft.,Unfurnished
...,...,...,...,...,...,...,...,...
53726,"Segambut, Kuala Lumpur","RM 2,650,000",4+2,6.0,NaN,Semi-detached House (Corner),Land area : 4700 sq. ft.,Unfurnished
53735,"Segambut, Kuala Lumpur","RM 2,700,000",5+1,6.0,NaN,Semi-detached House (Intermediate),Land area : 40X80 sq. ft.,Partly Furnished
53749,"Segambut, Kuala Lumpur","RM 2,100,000",5+1,5.0,3.0,Semi-detached House (Intermediate),"Built-up : 3,068 sq. ft.",Partly Furnished
53785,"Segambut, Kuala Lumpur","RM 1,250,000",4+1,6.0,2.0,3-sty Terrace/Link House (Intermediate),Land area : 22X70 sq. ft.,Unfurnished
53786,"Segambut, Kuala Lumpur","RM 1,300,000",4+1,6.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 21X70 sq. ft.,Unfurnished

In [87]:
#Bt Caves cluster

btc = all_nan[all_nan['Location'].str.contains('Caves')]
btc

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
220,"Batu Caves, Kuala Lumpur","RM 468,000",3,2.0,2.0,Serviced Residence,NaN,Partly Furnished
249,"Batu Caves, Kuala Lumpur","RM 676,775",3+1,3.0,4.0,Serviced Residence (Intermediate),"Built-up : 1,265 sq. ft.",Partly Furnished
886,"Batu Caves, Kuala Lumpur","RM 730,000",3,2.0,2.0,Serviced Residence (Intermediate),"Built-up : 1,227 sq. ft.",Partly Furnished
1830,"Batu Caves, Kuala Lumpur","RM 330,000",3,2.0,NaN,Townhouse,"Built-up : 1,275 sq. ft.",Partly Furnished
2017,"Batu Caves, Kuala Lumpur","RM 720,000",3,3.0,2.0,Serviced Residence,"Built-up : 1,227 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53490,"Batu Caves, Kuala Lumpur","RM 380,000",3,2.0,NaN,Condominium,"Built-up : 1,130 sq. ft.",Partly Furnished
53491,"Batu Caves, Kuala Lumpur","RM 380,000",3,2.0,NaN,Condominium,"Built-up : 1,130 sq. ft.",Partly Furnished
53499,"Batu Caves, Kuala Lumpur","RM 420,000",3,2.0,NaN,Condominium,"Built-up : 1,100 sq. ft.",Partly Furnished
53502,"Batu Caves, Kuala Lumpur","RM 685,000",3,2.0,2.0,Serviced Residence (Corner),"Built-up : 1,012 sq. ft.",Partly Furnished
53874,"Batu Caves, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,092 sq. ft.",Partly Furnished

In [88]:
#Wangsa Maju cluster

wm = all_nan[all_nan['Location'].str.contains('Wangsa Maju')]
wm

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
222,"Wangsa Maju, Kuala Lumpur","RM 700,000",3,2.0,2.0,Condominium,"Built-up : 1,152 sq. ft.",Partly Furnished
239,"Wangsa Maju, Kuala Lumpur","RM 350,000",3,2.0,2.0,Serviced Residence,NaN,Partly Furnished
376,"Wangsa Maju, Kuala Lumpur","RM 1,613,300",3+1,5.0,3.0,Condominium,"Built-up : 2,336 sq. ft.",Partly Furnished
664,"Wangsa Maju, Kuala Lumpur","RM 1,613,300",3+1,4.0,3.0,Condominium (Corner),"Built-up : 2,336 sq. ft.",Partly Furnished
665,"Wangsa Maju, Kuala Lumpur","RM 500,000",3,2.0,1.0,2-sty Terrace/Link House (Intermediate),Land area : 16 X55 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53616,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,1.0,Condominium,"Built-up : 1,150 sq. ft.",Unfurnished
53617,"Wangsa Maju, Kuala Lumpur","RM 485,000",3,2.0,1.0,Condominium,"Built-up : 1,150 sq. ft.",Unfurnished
53618,"Wangsa Maju, Kuala Lumpur","RM 490,000",3,2.0,1.0,Condominium,"Built-up : 1,150 sq. ft.",Unfurnished
53817,"Wangsa Maju, Kuala Lumpur","RM 1,300,000",5+1,4.0,2.0,3-sty Terrace/Link House (Intermediate),Land area : 24x85 sq. ft.,Partly Furnished
53881,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Unfurnished

In [203]:
#oug&yarl cluster

oug = all_nan[all_nan['Location'].str.contains('OUG|Yarl') == True]
oug

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
359,"OUG, Kuala Lumpur","RM 5,900,000",6+1,8.0,NaN,Bungalow (Corner),Land area : 12722 sq. ft.,Partly Furnished
718,"OUG, Kuala Lumpur","RM 2,398,000",5,3.0,8.0,Semi-detached House,Land area : 5000 sq. ft.,Fully Furnished
1184,"OUG, Kuala Lumpur","RM 1,450,000",4+1,5.0,2.0,Semi-detached House (Intermediate),Land area : 2809 sq. ft.,Partly Furnished
2657,"OUG, Kuala Lumpur","RM 1,600,000",5,5.0,3.0,Semi-detached House (Intermediate),Land area : 40x70 sq. ft.,Partly Furnished
2837,"OUG, Kuala Lumpur","RM 590,000",4,3.0,2.0,Townhouse (Intermediate),"Built-up : 1,711 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
52354,"OUG, Kuala Lumpur","RM 880,000",3,2.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Unfurnished
52527,"OUG, Kuala Lumpur","RM 2,100,000",5,5.0,NaN,Bungalow,Land area : 6410 sq. ft.,Partly Furnished
52815,"OUG, Kuala Lumpur","RM 570,000",3,3.0,2.0,Townhouse,"Built-up : 1,684 sq. ft.",Fully Furnished
52839,"OUG, Kuala Lumpur","RM 540,000",3,3.0,3.0,Townhouse (Intermediate),"Built-up : 1,684 sq. ft.",Partly Furnished
53856,"OUG, Kuala Lumpur","RM 2,900,000",5,4.0,4.0,Semi-detached House (Intermediate),Land area : 5100 sq. ft.,Partly Furnished

In [90]:
#Sri Hartamas cluster

sh = all_nan[all_nan['Location'].str.contains('Hartamas')]
sh

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
285,"Sri Hartamas, Kuala Lumpur","RM 14,800,000",4+2,6.0,4.0,Bungalow,Land area : 8611 sq. ft.,Fully Furnished
379,"Sri Hartamas, Kuala Lumpur","RM 7,300,000",6,6.0,6.0,Bungalow (Corner),Land area : 7300 sq. ft.,Partly Furnished
600,"Sri Hartamas, Kuala Lumpur","RM 3,450,000",4+1,5.0,3.0,Bungalow (Intermediate),Land area : 5200 sq. ft.,Partly Furnished
734,"Sri Hartamas, Kuala Lumpur","RM 9,000,000",5+1,6.0,NaN,Bungalow,Land area : 8100 sq. ft.,Partly Furnished
735,"Sri Hartamas, Kuala Lumpur","RM 12,000,000",7+1,8.0,NaN,Bungalow,Land area : 9700 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53842,"Sri Hartamas, Kuala Lumpur","RM 690,000",3+1,2.0,NaN,Serviced Residence (Corner),"Built-up : 1,230 sq. ft.",Fully Furnished
53843,"Sri Hartamas, Kuala Lumpur","RM 750,000",3+1,2.0,NaN,Serviced Residence (Corner),"Built-up : 1,230 sq. ft.",Fully Furnished
53844,"Sri Hartamas, Kuala Lumpur","RM 430,000",Studio,1.0,NaN,Serviced Residence (Corner),Built-up : 500 sq. ft.,Fully Furnished
53872,"Sri Hartamas, Kuala Lumpur","RM 3,150,000",4+1,5.0,NaN,Condominium (Duplex),"Built-up : 3,466 sq. ft.",Fully Furnished
53876,"Sri Hartamas, Kuala Lumpur","RM 2,700,000",4+2,6.0,3.0,Condominium (Corner),"Built-up : 3,973 sq. ft.",Partly Furnished

In [91]:
#J Sultan Ismail cluster

jsi = all_nan[all_nan['Location'].str.contains('Sultan Ismail')]
jsi

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
384,"Jalan Sultan Ismail, Kuala Lumpur","RM 495,000",1,1.0,NaN,Serviced Residence (Intermediate),Built-up : 560 sq. ft.,Fully Furnished
3409,"Jalan Sultan Ismail, Kuala Lumpur","RM 430,000",Studio,1.0,NaN,Serviced Residence,Built-up : 500 sq. ft.,Fully Furnished
3964,"Jalan Sultan Ismail, Kuala Lumpur","RM 930,000",2+1,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,300 sq. ft.",Fully Furnished
3965,"Jalan Sultan Ismail, Kuala Lumpur","RM 515,000",1,1.0,NaN,Serviced Residence (Intermediate),Built-up : 560 sq. ft.,Fully Furnished
3967,"Jalan Sultan Ismail, Kuala Lumpur","RM 440,000",Studio,1.0,NaN,Serviced Residence,NaN,Partly Furnished
...,...,...,...,...,...,...,...,...
50714,"Jalan Sultan Ismail, Kuala Lumpur","RM 520,000",Studio,1.0,NaN,Serviced Residence (Intermediate),Built-up : 500 sq. ft.,Fully Furnished
50715,"Jalan Sultan Ismail, Kuala Lumpur","RM 520,000",Studio,1.0,NaN,Serviced Residence (Intermediate),Built-up : 500 sq. ft.,Fully Furnished
52985,"Jalan Sultan Ismail, Kuala Lumpur","RM 1,080,000",2+1,2.0,NaN,Serviced Residence,"Built-up : 1,290 sq. ft.",Fully Furnished
53096,"Jalan Sultan Ismail, Kuala Lumpur","RM 830,000",2+1,3.0,NaN,Serviced Residence,"Built-up : 1,240 sq. ft.",Fully Furnished
53779,"Jalan Sultan Ismail, Kuala Lumpur","RM 450,000",Studio,1.0,NaN,Serviced Residence,Built-up : 500 sq. ft.,Fully Furnished

In [92]:
#Chan Sow Lin cluster

csl = all_nan[all_nan['Location'].str.contains('Chan')]
csl

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
385,"Chan Sow Lin, Kuala Lumpur","RM 569,200",1+1,2.0,2.0,Serviced Residence,Built-up : 888 sq. ft.,Unfurnished
20644,"Chan Sow Lin, Kuala Lumpur","RM 779,000",3,4.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,250 sq. ft.",Unfurnished
20645,"Chan Sow Lin, Kuala Lumpur","RM 570,000",2,2.0,1.0,Serviced Residence (Intermediate),Built-up : 888 sq. ft.,Unfurnished
25377,"Chan Sow Lin, Kuala Lumpur","RM 328,000",3,2.0,NaN,Townhouse,NaN,NaN
40199,"Chan Sow Lin, Kuala Lumpur","RM 804,000",3,4.0,2.0,Serviced Residence (Intermediate),"Built-up : 1,250 sq. ft.",Fully Furnished
40200,"Chan Sow Lin, Kuala Lumpur","RM 553,000",2,2.0,2.0,Serviced Residence,Built-up : 888 sq. ft.,Fully Furnished
44694,"Chan Sow Lin, Kuala Lumpur","RM 1,174,500",4+1,4.0,NaN,Semi-detached House,Land area : 3360 sq. ft.,Unfurnished
46097,"Chan Sow Lin, Kuala Lumpur","RM 420,000",2,2.0,1.0,Serviced Residence,Built-up : 695 sq. ft.,Unfurnished
52763,"Chan Sow Lin, Kuala Lumpur","RM 870,300",2,2.0,2.0,Serviced Residence (Intermediate),Land area : 1273 sq. ft.,Partly Furnished
52764,"Chan Sow Lin, Kuala Lumpur","RM 819,450",3,4.0,2.0,Serviced Residence (Intermediate),Land area : 1250 sq. ft.,Partly Furnished
52843,"Chan Sow Lin, Kuala Lumpur","RM 779,000",3,4.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,250 sq. ft.",Unfurnished

In [93]:
#KL Eco City cluster

eco = all_nan[all_nan['Location'].str.contains('Eco')]
eco

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
449,"KL Eco City, Kuala Lumpur","RM 1,200,000",NaN,NaN,NaN,Condominium,Built-up : 969 sq. ft.,NaN
554,"KL Eco City, Kuala Lumpur","RM 1,288,972",2,2.0,1.0,Condominium,"Built-up : 1,076 sq. ft.",Fully Furnished
666,"KL Eco City, Kuala Lumpur","RM 1,200,000",2,2.0,1.0,Condominium,Built-up : 969 sq. ft.,Partly Furnished
738,"KL Eco City, Kuala Lumpur","RM 780,000",1,1.0,1.0,Condominium,Built-up : 657 sq. ft.,Partly Furnished
793,"KL Eco City, Kuala Lumpur","RM 1,061,100",1+1,1.0,1.0,Condominium,Built-up : 786 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51411,"KL Eco City, Kuala Lumpur","RM 2,000,000",3,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,245 sq. ft.",Partly Furnished
53112,"KL Eco City, Kuala Lumpur","RM 1,804,275",2+1,2.0,2.0,Condominium,"Built-up : 1,646 sq. ft.",NaN
53635,"KL Eco City, Kuala Lumpur","RM 840,000",1,1.0,1.0,Condominium,Built-up : 657 sq. ft.,Fully Furnished
53797,"KL Eco City, Kuala Lumpur","RM 1,270,000",2,2.0,2.0,Condominium (Corner),"Built-up : 1,076 sq. ft.",Fully Furnished
53869,"KL Eco City, Kuala Lumpur","RM 880,000",1,1.0,1.0,Condominium (Corner),Built-up : 650 sq. ft.,Partly Furnished

In [111]:
#Ampang cluster

ampang = all_nan[all_nan['Location'].str.contains('Ampang')]
ampang


ampangonly = ampang[~ampang['Location'].str.contains('Hilir')]
ampangonly

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
282,"Ampang, Kuala Lumpur","RM 3,680,000",7,8.0,4.0,Bungalow (Corner),Land area : 6300 sq. ft.,Unfurnished
348,"Ampang, Kuala Lumpur","RM 560,000",1,1.0,1.0,Serviced Residence,NaN,Partly Furnished
511,"Ampang, Kuala Lumpur","RM 1,280,000",NaN,NaN,NaN,Residential Land,Land area : 100000 sq. ft.,NaN
513,"Ampang, Kuala Lumpur","RM 3,600,000",4+1,4.0,6.0,Bungalow (Intermediate),Land area : 9670 sq. ft.,Unfurnished
529,"Ampang, Kuala Lumpur","RM 2,590,000",5+1,6.0,2.0,Bungalow (Intermediate),Land area : 58x80 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53562,"Ampang, Kuala Lumpur","RM 630,000",1,1.0,1.0,Serviced Residence,Built-up : 853 sq. ft.,Partly Furnished
53659,"Ampang, Kuala Lumpur","RM 2,700,000",7,7.0,NaN,Semi-detached House,Land area : 7900 sq. ft.,Partly Furnished
53825,"Ampang, Kuala Lumpur","RM 2,290,000",5+1,6.0,NaN,Bungalow (Intermediate),Land area : 1 acre sq. ft.,Unfurnished
53854,"Ampang, Kuala Lumpur","RM 2,150,000",6,6.0,NaN,Semi-detached House (Intermediate),Land area : 3200 sq. ft.,Partly Furnished
53860,"Ampang, Kuala Lumpur","RM 490,000",1,1.0,1.0,Serviced Residence,Built-up : 705 sq. ft.,Partly Furnished

In [113]:
#Setiawangsa cluster

swg = all_nan[all_nan['Location'].str.contains('Setiawangsa')]
swg

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
347,"Setiawangsa, Kuala Lumpur","RM 590,000",3,2.0,2.0,Condominium (Intermediate),"Built-up : 1,196 sq. ft.",Partly Furnished
2772,"Setiawangsa, Kuala Lumpur","RM 1,650,000",4,3.0,2.0,2-sty Terrace/Link House,Land area : 2000 sq. ft.,Partly Furnished
3069,"Setiawangsa, Kuala Lumpur","RM 590,000",3,2.0,2.0,Condominium (Corner),"Built-up : 1,196 sq. ft.",Partly Furnished
3070,"Setiawangsa, Kuala Lumpur","RM 590,000",3,2.0,2.0,Condominium (Intermediate),"Built-up : 1,196 sq. ft.",Partly Furnished
3819,"Setiawangsa, Kuala Lumpur","RM 610,000",3,2.0,2.0,Condominium,"Built-up : 1,196 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
52938,"Setiawangsa, Kuala Lumpur","RM 2,500,000",3,3.0,4.0,Semi-detached House (Corner),Land area : 4326 sq. ft.,Fully Furnished
53309,"Setiawangsa, Kuala Lumpur","RM 1,350,000",4+1,3.0,2.0,2-sty Terrace/Link House (Corner),Land area : 25x70 sq. ft.,Partly Furnished
53452,"Setiawangsa, Kuala Lumpur","RM 2,500,000",NaN,NaN,NaN,Bungalow,"Built-up : 5,200 sq. ft.",Partly Furnished
53476,"Setiawangsa, Kuala Lumpur","RM 870,000",4+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1400 sq. ft.,NaN
53827,"Setiawangsa, Kuala Lumpur","RM 3,200,000",4+1,3.0,4.0,2-sty Terrace/Link House (Corner),Land area : 3627 sq. ft.,Partly Furnished

In [115]:
#Bdr Menjalara cluster

bm = all_nan[all_nan['Location'].str.contains('Menjalara')]
bm

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
426,"Bandar Menjalara, Kuala Lumpur","RM 888,000",4+1,3.0,NaN,2-sty Terrace/Link House,Land area : 22x80 sq. ft.,Unfurnished
914,"Bandar Menjalara, Kuala Lumpur","RM 430,000",3,2.0,2.0,Condominium (Intermediate),"Built-up : 1,076 sq. ft.",Unfurnished
1091,"Bandar Menjalara, Kuala Lumpur","RM 850,000",4,3.0,2.0,2-sty Terrace/Link House,Land area : 22 X 80 sq. ft.,Partly Furnished
1092,"Bandar Menjalara, Kuala Lumpur","RM 560,000",3,2.0,2.0,2-sty Terrace/Link House,Land area : 770 sq. ft.,Partly Furnished
1335,"Bandar Menjalara, Kuala Lumpur","RM 1,680,000",6,4.0,2.0,2-sty Terrace/Link House (Corner),Land area : 42 x 85 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53681,"Bandar Menjalara, Kuala Lumpur","RM 610,000",3+1,2.0,1.0,Condominium (Intermediate),"Built-up : 1,312 sq. ft.",Fully Furnished
53692,"Bandar Menjalara, Kuala Lumpur","RM 4,980,000",6,5.0,NaN,Semi-detached House (Corner),Land area : 5296 sq. ft.,Partly Furnished
53715,"Bandar Menjalara, Kuala Lumpur","RM 680,000",3,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 16x55 sq. ft.,Partly Furnished
53822,"Bandar Menjalara, Kuala Lumpur","RM 3,350,000",5+1,6.0,2.0,Semi-detached House,Land area : 45x90 sq. ft.,NaN
53858,"Bandar Menjalara, Kuala Lumpur","RM 525,000",3,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 1157 sq. ft.,Partly Furnished

In [117]:
#Sunway SPK cluster

sunwayspk = all_nan[all_nan['Location'].str.contains('Sunway SPK')]
sunwayspk

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
545,"Sunway SPK, Kuala Lumpur","RM 1,600,000",5+1,5.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
951,"Sunway SPK, Kuala Lumpur","RM 1,600,000",4+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
954,"Sunway SPK, Kuala Lumpur","RM 1,200,000",3+1,4.0,NaN,Townhouse (Intermediate),Land area : 26x87 sq. ft.,Partly Furnished
955,"Sunway SPK, Kuala Lumpur","RM 1,600,000",5+1,5.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
1142,"Sunway SPK, Kuala Lumpur","RM 3,600,000",5+1,5.0,6.0,Semi-detached House (Intermediate),Land area : 45x103 sq. ft.,Fully Furnished
...,...,...,...,...,...,...,...,...
53198,"Sunway SPK, Kuala Lumpur","RM 1,650,000",5+1,5.0,NaN,2-sty Terrace/Link House,Land area : 22x75 sq. ft.,NaN
53299,"Sunway SPK, Kuala Lumpur","RM 1,250,000",4,4.0,2.0,Townhouse (Intermediate),Land area : 26x87 sq. ft.,NaN
53585,"Sunway SPK, Kuala Lumpur","RM 1,400,000",3+1,4.0,NaN,Townhouse (Corner),"Built-up : 2,800 sq. ft.",Partly Furnished
53736,"Sunway SPK, Kuala Lumpur","RM 1,250,000",3+1,4.0,NaN,Townhouse (Intermediate),"Built-up : 2,600 sq. ft.",Partly Furnished
53848,"Sunway SPK, Kuala Lumpur","RM 3,100,000",5+1,5.0,NaN,Semi-detached House (Intermediate),Land area : 45x90 sq. ft.,Partly Furnished

In [119]:
#Pantai cluster

pantai = all_nan[all_nan['Location'].str.contains('Pantai')]
pantai

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
567,"Pantai, Kuala Lumpur","RM 570,000",3,2.0,1.0,Condominium (Corner),Land area : 1200 sq. ft.,Partly Furnished
1866,"Pantai, Kuala Lumpur","RM 720,000",3,2.0,2.0,Condominium (Corner),"Built-up : 1,019 sq. ft.",Fully Furnished
2505,"Pantai, Kuala Lumpur","RM 4,500,000",5+1,5.0,NaN,Bungalow,Land area : 8300 sq. ft.,NaN
2506,"Pantai, Kuala Lumpur","RM 5,500,000",4+1,5.0,NaN,Bungalow,Land area : Malaysia sq. ft.,NaN
2758,"Pantai, Kuala Lumpur","RM 820,000",1,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,300 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53703,"Pantai, Kuala Lumpur","RM 1,700,000",4+1,4.0,4.0,Condominium (Corner),"Built-up : 2,415 sq. ft.",Unfurnished
53723,"Pantai, Kuala Lumpur","RM 1,200,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,646 sq. ft.",Partly Furnished
53755,"Pantai, Kuala Lumpur","RM 800,000",3,2.0,2.0,Condominium (Corner),"Built-up : 1,253 sq. ft.",Unfurnished
53781,"Pantai, Kuala Lumpur","RM 660,000",3,2.0,NaN,Condominium (Corner),"Built-up : 1,250 sq. ft.",Fully Furnished
53831,"Pantai, Kuala Lumpur","RM 730,000",3,2.0,2.0,Condominium (Corner),"Built-up : 1,209 sq. ft.",Unfurnished

In [122]:
#Jalan Ipoh cluster

ipoh = all_nan[all_nan['Location'].str.contains('Ipoh')]
ipoh

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
977,"Jalan Ipoh, Kuala Lumpur","RM 561,100",3+1,4.0,NaN,Condominium (Penthouse),"Built-up : 1,879 sq. ft.",Partly Furnished
1153,"Jalan Ipoh, Kuala Lumpur","RM 561,100",3+1,4.0,NaN,Condominium (Penthouse),"Built-up : 1,879 sq. ft.",Unknown
1220,"Jalan Ipoh, Kuala Lumpur","RM 561,100",4,3.0,NaN,Condominium,"Built-up : 1,879 sq. ft.",Partly Furnished
1269,"Jalan Ipoh, Kuala Lumpur","RM 388,000",2,1.0,1.0,Condominium (Corner),Built-up : 700 sq. ft.,Fully Furnished
1588,"Jalan Ipoh, Kuala Lumpur","RM 420,000",3,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,020 sq. ft.",Unfurnished
...,...,...,...,...,...,...,...,...
53660,"Jalan Ipoh, Kuala Lumpur","RM 420,000",3,2.0,1.0,Condominium (Corner),Land area : 1020 sq. ft.,Unfurnished
53679,"Jalan Ipoh, Kuala Lumpur","RM 600,000",3,2.0,1.0,Condominium (Intermediate),"Built-up : 1,275 sq. ft.",Partly Furnished
53718,"Jalan Ipoh, Kuala Lumpur","RM 680,000",3,3.0,2.0,Townhouse (Intermediate),"Built-up : 1,814 sq. ft.",Partly Furnished
53772,"Jalan Ipoh, Kuala Lumpur","RM 736,200",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,227 sq. ft.",Partly Furnished
53773,"Jalan Ipoh, Kuala Lumpur","RM 642,800",3,2.0,NaN,Condominium (Corner),"Built-up : 1,070 sq. ft.",Partly Furnished

In [124]:
#Mid Valley cluster

mv = all_nan[all_nan['Location'].str.contains('Mid')]
mv

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1072,"Mid Valley City, Kuala Lumpur","RM 1,280,000",2+1,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
1101,"Mid Valley City, Kuala Lumpur","RM 1,350,000",3,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
1474,"Mid Valley City, Kuala Lumpur","RM 1,250,000",2+1,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
4169,"Mid Valley City, Kuala Lumpur","RM 2,500,000",3+1,3.0,1.0,Condominium,"Built-up : 2,680 sq. ft.",Partly Furnished
4205,"Mid Valley City, Kuala Lumpur","RM 1,700,000",3+1,4.0,NaN,Condominium (Corner),"Built-up : 1,819 sq. ft.",Fully Furnished
4206,"Mid Valley City, Kuala Lumpur","RM 1,400,000",3,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
4353,"Mid Valley City, Kuala Lumpur","RM 1,780,000",4,3.0,NaN,Condominium (Corner),"Built-up : 1,905 sq. ft.",Fully Furnished
4357,"Mid Valley City, Kuala Lumpur","RM 1,450,000",2+1,2.0,NaN,Condominium (Corner),"Built-up : 1,356 sq. ft.",Fully Furnished
4358,"Mid Valley City, Kuala Lumpur","RM 1,850,000",3+1,4.0,1.0,Condominium (Corner),"Built-up : 1,819 sq. ft.",Fully Furnished
4359,"Mid Valley City, Kuala Lumpur","RM 1,400,000",2+1,2.0,NaN,Condominium (Intermediate),"Built-up : 1,367 sq. ft.",Fully Furnished
6808,"Mid Valley City, Kuala Lumpur","RM 1,600,000",3+1,4.0,NaN,Condominium (Corner),"Built-up : 1,905 sq. ft.",Fully Furnished
7190,"Mid Valley City, Kuala Lumpur","RM 1,700,000",3+1,4.0,NaN,Condominium (Corner),"Built-up : 1,819 sq. ft.",Fully Furnished
8097,"Mid Valley City, Kuala Lumpur","RM 1,250,000",2+1,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
8836,"Mid Valley City, Kuala Lumpur","RM 1,780,000",3+1,3.0,NaN,Condominium (Intermediate),"Built-up : 1,905 sq. ft.",Fully Furnished
8927,"Mid Valley City, Kuala Lumpur","RM 2,100,000",3+1,4.0,NaN,Condominium,"Built-up : 1,906 sq. ft.",Fully Furnished
10780,"Mid Valley City, Kuala Lumpur","RM 560,000",1,2.0,1.0,Condominium (Corner),Built-up : 667 sq. ft.,Fully Furnished
11936,"Mid Valley City, Kuala Lumpur","RM 1,460,000",3,2.0,NaN,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
11937,"Mid Valley City, Kuala Lumpur","RM 2,600,000",5,5.0,NaN,Bungalow (Corner),Land area : 2680 sq. ft.,Unfurnished
11938,"Mid Valley City, Kuala Lumpur","RM 1,260,000",3,2.0,NaN,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
13315,"Mid Valley City, Kuala Lumpur","RM 1,450,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,367 sq. ft.",Fully Furnished
17548,"Mid Valley City, Kuala Lumpur","RM 1,450,000",3,2.0,2.0,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
17549,"Mid Valley City, Kuala Lumpur","RM 1,400,000",3,2.0,2.0,Condominium (Intermediate),"Built-up : 1,367 sq. ft.",Fully Furnished
19220,"Mid Valley City, Kuala Lumpur","RM 1,400,000",3,2.0,NaN,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
20784,"Mid Valley City, Kuala Lumpur","RM 1,700,000",3+1,4.0,NaN,Condominium (Corner),"Built-up : 1,819 sq. ft.",Fully Furnished
20965,"Mid Valley City, Kuala Lumpur","RM 385,000",1,1.0,1.0,2-sty Terrace/Link House,Built-up : 452 sq. ft.,Partly Furnished
20967,"Mid Valley City, Kuala Lumpur","RM 430,000",2,1.0,1.0,2-sty Terrace/Link House,Built-up : 492 sq. ft.,Partly Furnished
22669,"Mid Valley City, Kuala Lumpur","RM 1,250,000",2+1,2.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
22884,"Mid Valley City, Kuala Lumpur","RM 2,800,000",3+1,3.0,NaN,Condominium,"Built-up : 2,637 sq. ft.",Partly Furnished
25061,"Mid Valley City, Kuala Lumpur","RM 1,680,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,367 sq. ft.",Fully Furnished
26147,"Mid Valley City, Kuala Lumpur","RM 1,250,000",2+1,3.0,NaN,Condominium (Corner),"Built-up : 1,367 sq. ft.",Fully Furnished
26509,"Mid Valley City, Kuala Lumpur","RM 1,600,000",4,4.0,2.0,Condominium,"Built-up : 1,905 sq. ft.",Partly Furnished
29669,"Mid Valley City, Kuala Lumpur","RM 1,350,000",3,2.0,NaN,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
29670,"Mid Valley City, Kuala Lumpur","RM 1,350,000",3,2.0,NaN,Condominium,"Built-up : 1,367 sq. ft.",Fully Furnished
29671,"Mid Valley City, Kuala Lumpur","RM 1,356,000",3,2.0,NaN,Condominium,"Built-up : 1,356 sq. ft.",Fully Furnished
29688,"Mid Valley City, Kuala Lumpur","RM 2,800,000",3,2.0,NaN,Condominium (Corner),"Built-up : 2,637 sq. ft.",Fully Furnished
29689,"Mid Valley City, Kuala Lumpur","RM 1,330,000",3+1,4.0,1.0,Condominium (Corner),"Built-up : 1,356 sq. ft.",Fully Furnished
29925,"Mid Valley City, Kuala Lumpur","RM 2,250,000",3+1,4.0,NaN,Condominium,"Built-up : 1,900 sq. ft.",Fully Furnished
30307,"Mid Valley City, Kuala Lumpur","RM 300,000",NaN,NaN,NaN,Flat,Built-up : 750 sq. ft.,NaN
31188,"Mid Valley City, Kuala Lumpur","RM 1,300,000",3,2.0,NaN,Condominium,"Built-up : 1,356 sq. ft.",Fully Furnished
33213,"Mid Valley City, Kuala Lumpur","RM 1,800,000",3+1,4.0,NaN,Condominium,"Built-up : 1,819 sq. ft.",Unknown
33227,"Mid Valley City, Kuala Lumpur","RM 1,800,000",3+1,4.0,NaN,Condominium,"Built-up : 1,819 sq. ft.",Unknown
36930,"Mid Valley City, Kuala Lumpur","RM 5,000,000",11,7.0,8.0,Bungalow,Land area : 7800 sq. ft.,Partly Furnished
39713,"Mid Valley City, Kuala Lumpur","RM 9,220,000",NaN,NaN,NaN,Residential Land,Land area : 23056 sq. ft.,NaN
40167,"Mid Valley City, Kuala Lumpur","RM 1,800,000",3+1,3.0,NaN,Condominium,Land area : 1819 sq. ft.,Unfurnished
46478,"Mid Valley City, Kuala Lumpur","RM 1,380,000",3,2.0,NaN,Condominium,"Built-up : 1,356 sq. ft.",Fully Furnished
47492,"Mid Valley City, Kuala Lumpur","RM 1,500,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,367 sq. ft.",Fully Furnished
49211,"Mid Valley City, Kuala Lumpur","RM 1,700,000",3+1,4.0,1.0,Condominium (Corner),"Built-up : 1,905 sq. ft.",Fully Furnished
49212,"Mid Valley City, Kuala Lumpur","RM 2,000,000",3+1,4.0,1.0,Condominium (Corner),"Built-up : 1,905 sq. ft.",Fully Furnished
49512,"Mid Valley City, Kuala Lumpur","RM 2,900,700",3+2,5.0,NaN,Condominium (Corner),"Built-up : 2,637 sq. ft.",Partly Furnished
51118,"Mid Valley City, Kuala Lumpur","RM 9,220,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 23056 sq. ft.,NaN

In [127]:
#Brickfields cluster

bck = all_nan[all_nan['Location'].str.contains('Brickfields')]
bck

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1195,"Brickfields, Kuala Lumpur","RM 560,000",3,2.0,1.0,Condominium,"Built-up : 1,120 sq. ft.",NaN
1360,"Brickfields, Kuala Lumpur","RM 638,000",Studio,1.0,NaN,Serviced Residence (Intermediate),Built-up : 468 sq. ft.,Fully Furnished
2554,"Brickfields, Kuala Lumpur","RM 590,000",Studio,1.0,NaN,Serviced Residence,Built-up : 527 sq. ft.,Fully Furnished
2600,"Brickfields, Kuala Lumpur","RM 620,000",3,2.0,1.0,Serviced Residence,"Built-up : 1,200 sq. ft.",Fully Furnished
2601,"Brickfields, Kuala Lumpur","RM 1,200,000",4,3.0,3.0,Serviced Residence,"Built-up : 1,722 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53436,"Brickfields, Kuala Lumpur","RM 303,000",Studio,1.0,NaN,Serviced Residence,Built-up : 250 sq. ft.,Fully Furnished
53463,"Brickfields, Kuala Lumpur","RM 691,000",Studio,1.0,NaN,Serviced Residence (Intermediate),Built-up : 629 sq. ft.,Fully Furnished
53464,"Brickfields, Kuala Lumpur","RM 775,000",Studio,1.0,NaN,Serviced Residence (Corner),Built-up : 703 sq. ft.,Fully Furnished
53646,"Brickfields, Kuala Lumpur","RM 1,100,000",3,3.0,2.0,Condominium,"Built-up : 1,670 sq. ft.",NaN
53774,"Brickfields, Kuala Lumpur","RM 1,130,000",4,3.0,NaN,Condominium,"Built-up : 1,443 sq. ft.",NaN

In [129]:
#Desa Pandan cluster

dp = all_nan[all_nan['Location'].str.contains('Desa Pandan')]
dp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1297,"Desa Pandan, Kuala Lumpur","RM 1,300,000",3+1,2.0,2.0,Serviced Residence,"Built-up : 1,538 sq. ft.",Partly Furnished
1298,"Desa Pandan, Kuala Lumpur","RM 760,000",2,2.0,2.0,Serviced Residence (Corner),"Built-up : 1,087 sq. ft.",Partly Furnished
1299,"Desa Pandan, Kuala Lumpur","RM 750,000",2,2.0,2.0,Serviced Residence,NaN,Fully Furnished
1300,"Desa Pandan, Kuala Lumpur","RM 1,050,000",2,2.0,2.0,Serviced Residence (Intermediate),"Built-up : 1,410 sq. ft.",Partly Furnished
1887,"Desa Pandan, Kuala Lumpur","RM 1,550,000",3+1,4.0,2.0,Serviced Residence (Corner),"Built-up : 1,539 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
52650,"Desa Pandan, Kuala Lumpur","RM 1,260,000",2+1,2.0,2.0,Serviced Residence (Intermediate),"Built-up : 1,427 sq. ft.",Partly Furnished
52651,"Desa Pandan, Kuala Lumpur","RM 1,260,000",2+1,2.0,2.0,Serviced Residence (EndLot),"Built-up : 1,427 sq. ft.",Partly Furnished
52931,"Desa Pandan, Kuala Lumpur","RM 330,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 900 sq. ft.,Unfurnished
53015,"Desa Pandan, Kuala Lumpur","RM 270,000",4,2.0,NaN,Apartment,Built-up : 721 sq. ft.,Fully Furnished
53531,"Desa Pandan, Kuala Lumpur","RM 800,000",2,2.0,2.0,Serviced Residence,"Built-up : 1,076 sq. ft.",Partly Furnished

In [131]:
#Keramat cluster

keramat = all_nan[all_nan['Location'].str.contains('Keramat')]
keramat

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1424,"Keramat, Kuala Lumpur","RM 18,500,000",NaN,NaN,NaN,Residential Land,Land area : 41707 sq. ft.,NaN
3026,"Keramat, Kuala Lumpur","RM 1,200,000",4,5.0,2.0,3-sty Terrace/Link House (Intermediate),Land area : 1800 sq. ft.,Fully Furnished
3354,"Keramat, Kuala Lumpur","RM 1,200,000",3,4.0,NaN,Condominium (Intermediate),"Built-up : 1,800 sq. ft.",Fully Furnished
3494,"Keramat, Kuala Lumpur","RM 710,000",4,4.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
3792,"Keramat, Kuala Lumpur","RM 130,000",NaN,NaN,NaN,Flat,"Built-up : 54,200 sq. ft.",NaN
...,...,...,...,...,...,...,...,...
52550,"Keramat, Kuala Lumpur","RM 620,000",2,2.0,2.0,Condominium,Built-up : 943 sq. ft.,NaN
52613,"Keramat, Kuala Lumpur","RM 880,000",2,2.0,NaN,Condominium,Built-up : 943 sq. ft.,NaN
52828,"Keramat, Kuala Lumpur","RM 410,000",3,2.0,1.0,Condominium (Corner),Built-up : 912 sq. ft.,Partly Furnished
53008,"Keramat, Kuala Lumpur","RM 980,000",3+1,3.0,1.0,Condominium,"Built-up : 1,700 sq. ft.",NaN
53536,"Keramat, Kuala Lumpur","RM 1,250,000",4+1,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 2925 sq. ft.,Unfurnished

In [133]:
#Pandan Indah cluster

pi = all_nan[all_nan['Location'].str.contains('Pandan Indah')]
pi

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1675,"Pandan Indah, Kuala Lumpur","RM 659,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1400 sq. ft.,Partly Furnished
3288,"Pandan Indah, Kuala Lumpur","RM 1,230,000",6,4.0,4.0,Townhouse,Land area : 4900 sq. ft.,Partly Furnished
3365,"Pandan Indah, Kuala Lumpur","RM 830,000",5+1,3.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 1400 sq. ft.,NaN
4244,"Pandan Indah, Kuala Lumpur","RM 310,000",2,2.0,1.0,Townhouse,Built-up : 750 sq. ft.,NaN
4541,"Pandan Indah, Kuala Lumpur","RM 828,000",4,2.0,NaN,2-sty Terrace/Link House,Land area : 18x65 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51697,"Pandan Indah, Kuala Lumpur","RM 390,000",3,2.0,2.0,Townhouse (Intermediate),Built-up : 990 sq. ft.,Partly Furnished
52565,"Pandan Indah, Kuala Lumpur","RM 210,000",3,1.0,NaN,Flat,Built-up : 710 sq. ft.,Partly Furnished
52984,"Pandan Indah, Kuala Lumpur","RM 730,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 18x60 sq. ft.,Unfurnished
53151,"Pandan Indah, Kuala Lumpur","RM 595,000",4,2.0,NaN,2-sty Terrace/Link House,NaN,NaN
53449,"Pandan Indah, Kuala Lumpur","RM 600,000",5,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,300 sq. ft.",Unfurnished

In [135]:
#Federal Hill cluster

fh = all_nan[all_nan['Location'].str.contains('Federal')]
fh

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2043,"Federal Hill, Kuala Lumpur","RM 5,950,000",6+1,6.0,NaN,Bungalow (Intermediate),Land area : 9548 sq. ft.,Partly Furnished
3355,"Federal Hill, Kuala Lumpur","RM 3,180,000",4+1,6.0,NaN,Townhouse (Intermediate),"Built-up : 3,900 sq. ft.",Partly Furnished
3356,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,6.0,NaN,Townhouse (Corner),Land area : 3300 sq. ft.,Partly Furnished
3358,"Federal Hill, Kuala Lumpur","RM 4,600,000",4+1,6.0,NaN,Semi-detached House (Intermediate),Land area : 7950 sq. ft.,Partly Furnished
3743,"Federal Hill, Kuala Lumpur","RM 15,800,000",7+1,6.0,NaN,Bungalow,Land area : 12240 sq. ft.,NaN
5226,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,5.0,2.0,Townhouse (Intermediate),"Built-up : 4,000 sq. ft.",Partly Furnished
6689,"Federal Hill, Kuala Lumpur","RM 3,350,000",4+1,5.0,4.0,3.5-sty Terrace/Link House (Intermediate),Land area : 3326 sq. ft.,Partly Furnished
7481,"Federal Hill, Kuala Lumpur","RM 8,000,000",8+1,6.0,6.0,Bungalow (Corner),Land area : 12100 sq. ft.,Partly Furnished
7482,"Federal Hill, Kuala Lumpur","RM 7,500,000",4+1,3.0,6.0,Bungalow (Corner),Land area : 12000 sq. ft.,Partly Furnished
8776,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,6.0,NaN,Townhouse (Corner),Land area : 3300 sq. ft.,Partly Furnished
21298,"Federal Hill, Kuala Lumpur","RM 11,800,000",5+1,7.0,NaN,Bungalow (Intermediate),Land area : 10200 sq. ft.,Partly Furnished
21301,"Federal Hill, Kuala Lumpur","RM 3,350,000",4+1,6.0,NaN,Townhouse (Corner),"Built-up : 4,200 sq. ft.",Partly Furnished
21304,"Federal Hill, Kuala Lumpur","RM 8,000,000",5+1,7.0,NaN,Bungalow (Intermediate),Land area : 9000 sq. ft.,Partly Furnished
21333,"Federal Hill, Kuala Lumpur","RM 9,000,000",11,11.0,6.0,Bungalow (Corner),Land area : 11897 sq. ft.,Fully Furnished
21352,"Federal Hill, Kuala Lumpur","RM 15,900,000",NaN,NaN,NaN,Residential Land,Land area : 12240 sq. ft.,NaN
27702,"Federal Hill, Kuala Lumpur","RM 15,900,000",7+1,5.0,NaN,Bungalow (Intermediate),Land area : 12240sf sq. ft.,Partly Furnished
29398,"Federal Hill, Kuala Lumpur","RM 8,000,000",5+2,7.0,6.0,Bungalow (Intermediate),Land area : 8000 sq. ft.,Partly Furnished
31567,"Federal Hill, Kuala Lumpur","RM 3,900,000",4+1,6.0,NaN,Townhouse (Corner),Land area : 3843 sq. ft.,Partly Furnished
31568,"Federal Hill, Kuala Lumpur","RM 6,500,000",5+1,6.0,NaN,Bungalow (Intermediate),Land area : 7700 sq. ft.,Partly Furnished
33492,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,4.0,NaN,Townhouse (Intermediate),Land area : 2200 sq. ft.,Partly Furnished
33833,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,6.0,NaN,Townhouse (Corner),Land area : 3500 sq. ft.,Partly Furnished
33913,"Federal Hill, Kuala Lumpur","RM 3,200,000",4+1,6.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 4000 sq. ft.,Partly Furnished
37105,"Federal Hill, Kuala Lumpur","RM 4,000,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 13000 sq. ft.,NaN
37344,"Federal Hill, Kuala Lumpur","RM 8,000,000",5+1,7.0,NaN,Bungalow (Intermediate),Land area : 8000 sq. ft.,Partly Furnished
37791,"Federal Hill, Kuala Lumpur","RM 15,900,000",3,1.0,NaN,Bungalow,NaN,Partly Furnished
38140,"Federal Hill, Kuala Lumpur","RM 1,500,000",5,2.0,2.0,3-sty Terrace/Link House,Land area : 24X70 sq. ft.,Partly Furnished
38315,"Federal Hill, Kuala Lumpur","RM 7,400,000",4+1,6.0,6.0,Bungalow,Land area : 7750 sq. ft.,NaN
44442,"Federal Hill, Kuala Lumpur","RM 1,550,000",5,4.0,NaN,3-sty Terrace/Link House,"Built-up : 1,700 sq. ft.",Partly Furnished
47093,"Federal Hill, Kuala Lumpur","RM 3,700,000",4+1,6.0,NaN,Townhouse (Intermediate),Land area : 3843 sq. ft.,Partly Furnished
47094,"Federal Hill, Kuala Lumpur","RM 3,300,000",4+1,5.0,NaN,Townhouse (EndLot),Land area : 3000 sq. ft.,Partly Furnished
48915,"Federal Hill, Kuala Lumpur","RM 3,380,000",4+1,5.0,NaN,3.5-sty Terrace/Link House (Intermediate),"Built-up : 4,000 sq. ft.",Partly Furnished
50215,"Federal Hill, Kuala Lumpur","RM 11,100,000",6,6.0,6.0,Bungalow,Land area : 11000 sq. ft.,Fully Furnished
51507,"Federal Hill, Kuala Lumpur","RM 7,500,000",5+2,7.0,NaN,Bungalow (Intermediate),Land area : 8000 sq. ft.,Partly Furnished
53055,"Federal Hill, Kuala Lumpur","RM 30,000,000",NaN,NaN,NaN,Residential Land,Land area : 25000 sq. ft.,NaN

In [137]:
#Desa Petaling cluster

desapet = all_nan[all_nan['Location'].str.contains('Desa Petaling')]
desapet

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1706,"Desa Petaling, Kuala Lumpur","RM 265,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 830 sq. ft.,Partly Furnished
3451,"Desa Petaling, Kuala Lumpur","RM 3,230,000",4+1,5.0,NaN,Semi-detached House,Land area : 34x75 sq. ft.,Unknown
3503,"Desa Petaling, Kuala Lumpur","RM 130,000",2,1.0,1.0,Flat (Corner),Built-up : 550 sq. ft.,Partly Furnished
3506,"Desa Petaling, Kuala Lumpur","RM 325,000",3,2.0,1.0,Apartment (Intermediate),"Built-up : 1,016 sq. ft.",Partly Furnished
3772,"Desa Petaling, Kuala Lumpur","RM 360,000",3,2.0,1.0,Condominium,"Built-up : 1,016 sq. ft.",NaN
...,...,...,...,...,...,...,...,...
52802,"Desa Petaling, Kuala Lumpur","RM 360,000",3,2.0,2.0,Condominium,Built-up : 956 sq. ft.,NaN
52859,"Desa Petaling, Kuala Lumpur","RM 330,000",3,2.0,2.0,Condominium,Land area : 1009 sq. ft.,NaN
52861,"Desa Petaling, Kuala Lumpur","RM 330,000",3,2.0,2.0,Condominium,Land area : 1009 sq. ft.,NaN
53130,"Desa Petaling, Kuala Lumpur","RM 368,000",3,2.0,1.0,Condominium (Intermediate),"Built-up : 1,064 sq. ft.",Partly Furnished
53651,"Desa Petaling, Kuala Lumpur","RM 465,000",4,3.0,2.0,Condominium (Intermediate),"Built-up : 1,250 sq. ft.",Partly Furnished

In [139]:
#Pandan Perdana cluster

pp = all_nan[all_nan['Location'].str.contains('Pandan Perdana')]
pp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2622,"Pandan Perdana, Kuala Lumpur","RM 730,000",3,2.0,NaN,1-sty Terrace/Link House (Corner),Land area : 42x65 sq. ft.,Partly Furnished
2987,"Pandan Perdana, Kuala Lumpur","RM 24,680,000",NaN,NaN,NaN,Residential Land,Land area : 70543 sq. ft.,NaN
3080,"Pandan Perdana, Kuala Lumpur","RM 270,000",Studio,1.0,1.0,Condominium,Built-up : 450 sq. ft.,Partly Furnished
3820,"Pandan Perdana, Kuala Lumpur","RM 270,000",1,1.0,1.0,Condominium (SOHO),Built-up : 450 sq. ft.,Partly Furnished
4240,"Pandan Perdana, Kuala Lumpur","RM 275,000",1,1.0,1.0,Condominium,Built-up : 450 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
50519,"Pandan Perdana, Kuala Lumpur","RM 930,000",4+1,2.0,4.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
52509,"Pandan Perdana, Kuala Lumpur","RM 700,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x70 sq. ft.,Partly Furnished
52889,"Pandan Perdana, Kuala Lumpur","RM 710,000",4,2.0,5.0,2-sty Terrace/Link House (EndLot),Land area : 32X65 sq. ft.,Partly Furnished
53076,"Pandan Perdana, Kuala Lumpur","RM 765,000",3,2.0,NaN,1-sty Terrace/Link House (Corner),Land area : 2700 sq. ft.,NaN
53111,"Pandan Perdana, Kuala Lumpur","RM 500,000",4,2.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 18x60 sq. ft.,Unknown

In [141]:
#B Damai Perdana cluster

bdp = all_nan[all_nan['Location'].str.contains('Damai Perdana')]
bdp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2667,"Bandar Damai Perdana, Kuala Lumpur","RM 658,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1300 sq. ft.,Partly Furnished
2729,"Bandar Damai Perdana, Kuala Lumpur","RM 656,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x68 sq. ft.,Partly Furnished
3054,"Bandar Damai Perdana, Kuala Lumpur","RM 720,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 26x65 sq. ft.,Partly Furnished
3055,"Bandar Damai Perdana, Kuala Lumpur","RM 619,999",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 20x65 sq. ft.,Partly Furnished
3278,"Bandar Damai Perdana, Kuala Lumpur","RM 730,000",3+1,2.0,NaN,2-sty Terrace/Link House,Land area : 20 x70 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51610,"Bandar Damai Perdana, Kuala Lumpur","RM 545,000",4,3.0,4.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Unfurnished
52039,"Bandar Damai Perdana, Kuala Lumpur","RM 530,000",3,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 1170 sq. ft.,Partly Furnished
52584,"Bandar Damai Perdana, Kuala Lumpur","RM 630,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),"Built-up : 1,800 sq. ft.",Unfurnished
53696,"Bandar Damai Perdana, Kuala Lumpur","RM 600,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 20 x 65 sq. ft.,Partly Furnished
53819,"Bandar Damai Perdana, Kuala Lumpur","RM 990,000",6,4.0,NaN,Cluster House (Intermediate),Land area : 35X58 sq. ft.,Partly Furnished

In [143]:
#Puchong cluster

pcg = all_nan[all_nan['Location'].str.contains('Puchong')]
pcg

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2764,"Puchong, Kuala Lumpur","RM 900,000",6,6.0,NaN,3-sty Terrace/Link House,"Built-up : 3,600 sq. ft.",Fully Furnished
2935,"Puchong, Kuala Lumpur","RM 750,000",3,3.0,NaN,2-sty Terrace/Link House,Land area : 20x70 sq. ft.,NaN
3277,"Puchong, Kuala Lumpur","RM 600,000",3,2.0,NaN,1-sty Terrace/Link House,Land area : 20 x 70 sq. ft.,Partly Furnished
4035,"Puchong, Kuala Lumpur","RM 973,150",4+1,5.0,4.0,2-sty Terrace/Link House (Corner),Land area : 3756 sq. ft.,NaN
6728,"Puchong, Kuala Lumpur","RM 550,000",4,3.0,NaN,Semi-detached House (Intermediate),Land area : 35x50 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
53451,"Puchong, Kuala Lumpur","RM 970,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),"Built-up : 1,650 sq. ft.",NaN
53706,"Puchong, Kuala Lumpur","RM 5,480,000",7+1,7.0,8.0,Bungalow (Corner),Land area : 10500 sq. ft.,Fully Furnished
53812,"Puchong, Kuala Lumpur","RM 565,000",4,3.0,1.0,2-sty Terrace/Link House,"Built-up : 1,600 sq. ft.",Partly Furnished
53866,"Puchong, Kuala Lumpur","RM 710,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 20X70 sq. ft.,NaN
53867,"Puchong, Kuala Lumpur","RM 565,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 18x65 sq. ft.,NaN

In [147]:
#Salak Selatan cluster

ss = all_nan[all_nan['Location'].str.contains('Salak')]
ss

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3275,"Salak Selatan, Kuala Lumpur","RM 458,000",3,3.0,NaN,Serviced Residence,"Built-up : 1,045 sq. ft.",Fully Furnished
3428,"Salak Selatan, Kuala Lumpur","RM 402,000",2,2.0,1.0,Serviced Residence (Intermediate),Built-up : 850 sq. ft.,Fully Furnished
3631,"Salak Selatan, Kuala Lumpur","RM 2,900,000",5+1,7.0,6.0,Bungalow (Corner),Land area : 8878 sq. ft.,Partly Furnished
4196,"Salak Selatan, Kuala Lumpur","RM 384,000",2,2.0,1.0,Serviced Residence,NaN,NaN
4503,"Salak Selatan, Kuala Lumpur","RM 450,000",3,2.0,2.0,Serviced Residence,"Built-up : 1,000 sq. ft.",NaN
...,...,...,...,...,...,...,...,...
51576,"Salak Selatan, Kuala Lumpur","RM 625,000",3,2.0,1.0,Serviced Residence (Corner),"Built-up : 1,021 sq. ft.",NaN
52392,"Salak Selatan, Kuala Lumpur","RM 530,000",2,2.0,1.0,Serviced Residence,Built-up : 862 sq. ft.,Partly Furnished
52456,"Salak Selatan, Kuala Lumpur","RM 450,000",2,2.0,2.0,Serviced Residence (Intermediate),Built-up : 731 sq. ft.,Partly Furnished
52697,"Salak Selatan, Kuala Lumpur","RM 2,250,000",4,5.0,2.0,Bungalow (Intermediate),Land area : 4000 sq. ft.,Partly Furnished
53342,"Salak Selatan, Kuala Lumpur","RM 480,000",2,2.0,1.0,Serviced Residence (Intermediate),Built-up : 731 sq. ft.,Partly Furnished

In [149]:
#Titiwangsa cluster

tt = all_nan[all_nan['Location'].str.contains('Titiwangsa')]
tt

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3398,"Titiwangsa, Kuala Lumpur","RM 510,000",Studio,1.0,1.0,Serviced Residence (Studio),Built-up : 500 sq. ft.,NaN
3399,"Titiwangsa, Kuala Lumpur","RM 650,000",2,2.0,NaN,Serviced Residence,Built-up : 726 sq. ft.,NaN
3573,"Titiwangsa, Kuala Lumpur","RM 3,280,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 6000 sq. ft.,Partly Furnished
3630,"Titiwangsa, Kuala Lumpur","RM 610,000",3,2.0,1.0,Serviced Residence,"Built-up : 1,050 sq. ft.",Partly Furnished
3821,"Titiwangsa, Kuala Lumpur","RM 630,000",3,2.0,1.0,Serviced Residence,"Built-up : 1,100 sq. ft.",Fully Furnished
...,...,...,...,...,...,...,...,...
53189,"Titiwangsa, Kuala Lumpur","RM 17,716,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 30545 sq. ft.,NaN
53382,"Titiwangsa, Kuala Lumpur","RM 630,000",3,2.0,NaN,Serviced Residence (Intermediate),"Built-up : 1,100 sq. ft.",Fully Furnished
53828,"Titiwangsa, Kuala Lumpur","RM 8,000,000",7,6.0,6.0,Bungalow (Corner),Land area : 9795 sq. ft.,Partly Furnished
53829,"Titiwangsa, Kuala Lumpur","RM 5,300,000",4+1,5.0,3.0,Bungalow (Intermediate),Land area : 9950 sq. ft.,Partly Furnished
53830,"Titiwangsa, Kuala Lumpur","RM 2,600,000",5+1,5.0,4.0,Bungalow (Corner),Land area : 6050 sq. ft.,Partly Furnished

In [153]:
#Damansara cluster

damansara = all_nan[all_nan['Location'].str.contains('Damansara')]
damansara

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
17,"Damansara Heights, Kuala Lumpur","RM 4,500,000",5+1,7.0,NaN,Bungalow (Corner),"Built-up : 4,842 sq. ft.",Partly Furnished
21,"Damansara Heights, Kuala Lumpur","RM 1,550,000",1,1.0,1.0,Serviced Residence (Intermediate),Built-up : 904 sq. ft.,Fully Furnished
44,"Damansara Heights, Kuala Lumpur","RM 4,200,000",6,5.0,5.0,Bungalow,Land area : 5274 sq. ft.,Partly Furnished
107,"Damansara Heights, Kuala Lumpur","RM 6,800,000",5+2,7.0,NaN,Bungalow,Land area : 7000 sq. ft.,NaN
...,...,...,...,...,...,...,...,...
53721,"Damansara Heights, Kuala Lumpur","RM 6,670,888",5+1,6.0,NaN,Semi-detached House (EndLot),Land area : 24x85 sq. ft.,Partly Furnished
53722,"Damansara Heights, Kuala Lumpur","RM 5,231,888",5+1,6.0,NaN,Semi-detached House (Intermediate),Land area : 20x85 sq. ft.,Partly Furnished
53728,"Damansara Heights, Kuala Lumpur","RM 3,980,000",4+2,6.0,NaN,Semi-detached House (Intermediate),Land area : 40x98 sq. ft.,Partly Furnished
53870,"Damansara Heights, Kuala Lumpur","RM 3,500,000",NaN,NaN,NaN,Bungalow,NaN,NaN
53871,"Damansara Heights, Kuala Lumpur","RM 1,230,000",NaN,NaN,NaN,Bungalow,NaN,NaN

In [159]:
#Damansara cluster

damansaraonly = damansara[~damansara['Location'].str.contains('Heights')]
damansaraonly

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3701,"Damansara, Kuala Lumpur","RM 1,500,000",4+1,3.0,4.0,2-sty Terrace/Link House (Intermediate),Land area : 24x80 sq. ft.,Unfurnished
3971,"Damansara, Kuala Lumpur","RM 9,700,000",6,6.0,10.0,Bungalow,Land area : 81000 sq. ft.,Partly Furnished
4038,"Damansara, Kuala Lumpur","RM 1,088,000",4+1,5.0,4.0,Semi-detached House (Corner),Land area : 4004 sq. ft.,Unfurnished
6952,"Damansara, Kuala Lumpur","RM 3,300,000",5+1,7.0,3.0,Bungalow,Land area : 2572 sq. ft.,Partly Furnished
6955,"Damansara, Kuala Lumpur","RM 2,100,000",5+1,7.0,3.0,Semi-detached House,Land area : 2865 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51886,"Damansara, Kuala Lumpur","RM 920,000",4,3.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
52461,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
53097,"Damansara, Kuala Lumpur","RM 9,200,000",6+1,5.0,NaN,Bungalow,"Built-up : 8,365 sq. ft.",Partly Furnished
53383,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
53505,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished

In [160]:
#Damansara cluster

damansaraonly1 = damansaraonly[~damansaraonly['Location'].str.contains('Sri')]
damansaraonly1

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3701,"Damansara, Kuala Lumpur","RM 1,500,000",4+1,3.0,4.0,2-sty Terrace/Link House (Intermediate),Land area : 24x80 sq. ft.,Unfurnished
3971,"Damansara, Kuala Lumpur","RM 9,700,000",6,6.0,10.0,Bungalow,Land area : 81000 sq. ft.,Partly Furnished
4038,"Damansara, Kuala Lumpur","RM 1,088,000",4+1,5.0,4.0,Semi-detached House (Corner),Land area : 4004 sq. ft.,Unfurnished
6952,"Damansara, Kuala Lumpur","RM 3,300,000",5+1,7.0,3.0,Bungalow,Land area : 2572 sq. ft.,Partly Furnished
6955,"Damansara, Kuala Lumpur","RM 2,100,000",5+1,7.0,3.0,Semi-detached House,Land area : 2865 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
51414,"Damansara, Kuala Lumpur","RM 685,000",3,2.0,2.0,1-sty Terrace/Link House (Intermediate),Land area : 20x65 sq. ft.,Partly Furnished
51719,"Damansara, Kuala Lumpur","RM 7,200,000",10,12.0,NaN,2.5-sty Terrace/Link House,Land area : 44x120 sq. ft.,Partly Furnished
51881,"Damansara, Kuala Lumpur","RM 2,090,000",4+1,4.0,4.0,Semi-detached House (Intermediate),Land area : 45x75 sq. ft.,Partly Furnished
51886,"Damansara, Kuala Lumpur","RM 920,000",4,3.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
53097,"Damansara, Kuala Lumpur","RM 9,200,000",6+1,5.0,NaN,Bungalow,"Built-up : 8,365 sq. ft.",Partly Furnished

In [214]:
#B Sri Damansara cluster

bsd = all_nan[all_nan['Location'].str.contains('Bandar Sri Damansara|Sri damansara') == True]
bsd

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
28701,"Bandar Sri Damansara, Kuala Lumpur","RM 2,100,000",5+2,6.0,NaN,Semi-detached House (Intermediate),Land area : 2508 sq. ft.,Unfurnished
42410,"Bandar Sri damansara, Kuala Lumpur","RM 1,300,000",3+1,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22&#215;75 sq. ft.,NaN
50938,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
51480,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
52461,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
53383,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished
53505,"Bandar Sri Damansara, Kuala Lumpur","RM 930,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 1,650 sq. ft.",Partly Furnished

In [165]:
#BTS cluster

bts = all_nan[all_nan['Location'].str.contains('Tasik Selatan')]
bts

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3800,"Bandar Tasik Selatan, Kuala Lumpur","RM 180,000",NaN,NaN,NaN,Flat,Built-up : 657 sq. ft.,NaN
5610,"Bandar Tasik Selatan, Kuala Lumpur","RM 280,000",3,2.0,1.0,Flat (Corner),Built-up : 895 sq. ft.,Partly Furnished
5611,"Bandar Tasik Selatan, Kuala Lumpur","RM 295,000",3,2.0,1.0,Flat (Corner),Built-up : 895 sq. ft.,Partly Furnished
5612,"Bandar Tasik Selatan, Kuala Lumpur","RM 295,000",3,2.0,1.0,Flat (Corner),Built-up : 895 sq. ft.,Partly Furnished
5613,"Bandar Tasik Selatan, Kuala Lumpur","RM 295,000",3,2.0,1.0,Flat (Corner),Built-up : 895 sq. ft.,Partly Furnished
...,...,...,...,...,...,...,...,...
49456,"Bandar Tasik Selatan, Kuala Lumpur","RM 750,888",3,2.0,2.0,Condominium,Land area : 1242 sq. ft.,Partly Furnished
50474,"Bandar Tasik Selatan, Kuala Lumpur","RM 280,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 854 sq. ft.,Unfurnished
50752,"Bandar Tasik Selatan, Kuala Lumpur","RM 290,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 854 sq. ft.,Partly Furnished
51917,"Bandar Tasik Selatan, Kuala Lumpur","RM 270,000",3,2.0,NaN,Flat,Built-up : 880 sq. ft.,NaN
52041,"Bandar Tasik Selatan, Kuala Lumpur","RM 700,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 20x70 sq. ft.,NaN

In [168]:
#Alam Damai cluster

ad = all_nan[all_nan['Location'].str.contains('Alam Damai')]
ad

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
4130,"Alam Damai, Kuala Lumpur","RM 880,000",4,4.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1650 sq. ft.,Partly Furnished

In [170]:
#B Ledang cluster

bl = all_nan[all_nan['Location'].str.contains('Ledang')]
bl

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
4151,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",NaN,NaN,NaN,Bungalow,Land area : 4884 sq. ft.,Partly Furnished
11313,"Bukit Ledang, Kuala Lumpur",NaN,7+1,7.0,5.0,Bungalow,Land area : 20000 sq. ft.,NaN
16298,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",NaN,NaN,NaN,Bungalow,Land area : 4884 sq. ft.,Partly Furnished
18455,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",NaN,NaN,NaN,Bungalow,Land area : 4884 sq. ft.,Partly Furnished
19618,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",NaN,NaN,NaN,Bungalow,Land area : 4884 sq. ft.,Partly Furnished
19627,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",NaN,NaN,NaN,Bungalow,Land area : 4884 sq. ft.,Partly Furnished
21293,"Bukit Ledang, Kuala Lumpur","RM 2,750,000",4+1,5.0,2.0,Semi-detached House (Corner),Land area : 4000 sq. ft.,Partly Furnished
21324,"Bukit Ledang, Kuala Lumpur","RM 2,280,000",5,6.0,3.0,Bungalow,"Built-up : 4,884 sq. ft.",Partly Furnished
24070,"Bukit Ledang, Kuala Lumpur","RM 1,724,000",NaN,NaN,NaN,Bungalow,"Built-up : 4,884 sq. ft.",Unknown
24071,"Bukit Ledang, Kuala Lumpur","RM 1,724,000",NaN,NaN,NaN,Bungalow,"Built-up : 4,884 sq. ft.",Unknown
30123,"Bukit Ledang, Kuala Lumpur","RM 1,724,000",NaN,NaN,NaN,Bungalow,"Built-up : 4,884 sq. ft.",Unknown
36382,"Bukit Ledang, Kuala Lumpur","RM 1,723,500",5+1,7.0,NaN,Bungalow,Land area : 4884 sq. ft.,Unfurnished
38170,"Bukit Ledang, Kuala Lumpur","RM 2,600,000",4+1,6.0,4.0,Semi-detached House,Land area : 4000 sq. ft.,Partly Furnished
38609,"Bukit Ledang, Kuala Lumpur","RM 4,500,000",5+1,7.0,6.0,Bungalow (Corner),Land area : 5328 sq. ft.,Partly Furnished
51383,"Bukit Ledang, Kuala Lumpur","RM 12,000,000",8+1,10.0,NaN,Bungalow,Land area : 22000 sq. ft.,Partly Furnished

In [172]:
#Jinjang cluster

jj = all_nan[all_nan['Location'].str.contains('Jinjang')]
jj

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
4500,"Jinjang, Kuala Lumpur","RM 1,500,000",5,3.0,NaN,2-sty Terrace/Link House,Land area : 50x90 sq. ft.,NaN
4944,"Jinjang, Kuala Lumpur","RM 192,000",3,2.0,1.0,Apartment,Built-up : 720 sq. ft.,Partly Furnished
4981,"Jinjang, Kuala Lumpur","RM 295,000",3,1.0,2.0,2-sty Terrace/Link House (EndLot),Land area : 14x52 sq. ft.,Unfurnished
6700,"Jinjang, Kuala Lumpur","RM 605,000",3,2.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 16x55 sq. ft.,Unfurnished
8113,"Jinjang, Kuala Lumpur","RM 190,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 702 sq. ft.,Partly Furnished
8152,"Jinjang, Kuala Lumpur","RM 230,000",3,2.0,NaN,Apartment (Corner),Built-up : 720 sq. ft.,NaN
8493,"Jinjang, Kuala Lumpur","RM 1,200,000",5,4.0,NaN,2.5-sty Terrace/Link House,"Built-up : 3,000 sq. ft.",Partly Furnished
10482,"Jinjang, Kuala Lumpur","RM 1,100,000",5,4.0,2.0,2.5-sty Terrace/Link House (Intermediate),Land area : 3000 sq. ft.,Partly Furnished
10530,"Jinjang, Kuala Lumpur","RM 720,000",5,2.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 20x70 sq. ft.,Unfurnished
12514,"Jinjang, Kuala Lumpur","RM 615,000",3,2.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 16x55 sq. ft.,Unfurnished
12619,"Jinjang, Kuala Lumpur","RM 870,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 943 sq. ft.,Unfurnished
14015,"Jinjang, Kuala Lumpur","RM 189,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 720 sq. ft.,Partly Furnished
14827,"Jinjang, Kuala Lumpur","RM 308,000",3,2.0,1.0,Apartment,Built-up : 998 sq. ft.,Partly Furnished
17054,"Jinjang, Kuala Lumpur","RM 550,000",3,2.0,2.0,Serviced Residence,"Built-up : 1,136 sq. ft.",Partly Furnished
17294,"Jinjang, Kuala Lumpur","RM 138,000",3,1.0,NaN,Flat,Built-up : 650 sq. ft.,NaN
18730,"Jinjang, Kuala Lumpur","RM 190,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 720 sq. ft.,Unfurnished
19472,"Jinjang, Kuala Lumpur","RM 870,000",4,3.0,NaN,2-sty Terrace/Link House,"Built-up : 2,943 sq. ft.",NaN
20381,"Jinjang, Kuala Lumpur","RM 138,000",3,2.0,1.0,Flat,Land area : 650 sq. ft.,NaN
20404,"Jinjang, Kuala Lumpur","RM 328,000",3,2.0,1.0,Apartment (Intermediate),"Built-up : 328,000 sq. ft.",Partly Furnished
20406,"Jinjang, Kuala Lumpur","RM 298,000",3,1.0,1.0,Apartment (Corner),Built-up : 998 sq. ft.,Partly Furnished
22713,"Jinjang, Kuala Lumpur","RM 229,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 720 sq. ft.,Partly Furnished
23686,"Jinjang, Kuala Lumpur","RM 920,000",4,2.0,4.0,Bungalow,NaN,NaN
24958,"Jinjang, Kuala Lumpur","RM 140,000",3,2.0,NaN,Flat,Built-up : 650 sq. ft.,Partly Furnished
25709,"Jinjang, Kuala Lumpur","RM 1,120,000",4,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 3014 sq. ft.,NaN
25731,"Jinjang, Kuala Lumpur","RM 280,000",3,2.0,NaN,Apartment,Built-up : 856 sq. ft.,NaN
26020,"Jinjang, Kuala Lumpur","RM 310,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 999 sq. ft.,Unfurnished
27506,"Jinjang, Kuala Lumpur","RM 530,000",3,2.0,1.0,Serviced Residence (Intermediate),"Built-up : 1,136 sq. ft.",NaN
27747,"Jinjang, Kuala Lumpur","RM 599,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 2700 sq. ft.,Unknown
28615,"Jinjang, Kuala Lumpur","RM 315,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 855 sq. ft.,Partly Furnished
30203,"Jinjang, Kuala Lumpur","RM 145,000",3,2.0,NaN,Flat (Penthouse),Built-up : 650 sq. ft.,Partly Furnished
30298,"Jinjang, Kuala Lumpur","RM 298,000",3,2.0,1.0,Apartment (Corner),Built-up : 998 sq. ft.,Partly Furnished
30303,"Jinjang, Kuala Lumpur","RM 178,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 762 sq. ft.,Partly Furnished
30824,"Jinjang, Kuala Lumpur","RM 250,000",3,2.0,1.0,2-sty Terrace/Link House (Intermediate),Land area : 14x42 sq. ft.,Unfurnished
32672,"Jinjang, Kuala Lumpur",RM 900,1+2,2.0,NaN,Apartment (EndLot),Built-up : 657 sq. ft.,Unfurnished
33097,"Jinjang, Kuala Lumpur","RM 230,000",3,2.0,1.0,Apartment (Intermediate),Land area : 657 sq. ft.,Partly Furnished
33280,"Jinjang, Kuala Lumpur","RM 300,000",2,1.0,NaN,2-sty Terrace/Link House,Land area : 14x45 sq. ft.,Unfurnished
33806,"Jinjang, Kuala Lumpur","RM 480,000",3,2.0,1.0,1-sty Terrace/Link House (Corner),Land area : 2477 sq. ft.,Unfurnished
36131,"Jinjang, Kuala Lumpur","RM 1,500,000",NaN,NaN,NaN,Residential Land,NaN,NaN
38223,"Jinjang, Kuala Lumpur","RM 1,100,000",NaN,NaN,NaN,Apartment,Land area : 22x70 sq. ft.,NaN
39736,"Jinjang, Kuala Lumpur","RM 810,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 1600 sq. ft.,Partly Furnished
40910,"Jinjang, Kuala Lumpur","RM 328,000",3,2.0,1.0,Apartment (Intermediate),Built-up : 969 sq. ft.,Partly Furnished
42082,"Jinjang, Kuala Lumpur","RM 668,000",3,1.0,4.0,1-sty Terrace/Link House (Intermediate),Land area : 21x70 sq. ft.,Partly Furnished
42334,"Jinjang, Kuala Lumpur","RM 700,000",4,3.0,NaN,Bungalow,NaN,NaN
45035,"Jinjang, Kuala Lumpur","RM 560,000",3+1,2.0,2.0,Serviced Residence,"Built-up : 1,136 sq. ft.",Unfurnished
45044,"Jinjang, Kuala Lumpur","RM 560,000",3,2.0,NaN,Serviced Residence,"Built-up : 1,136 sq. ft.",Partly Furnished
45751,"Jinjang, Kuala Lumpur","RM 280,000",3+1,2.0,NaN,Flat,"Built-up : 1,140 sq. ft.",Partly Furnished
46309,"Jinjang, Kuala Lumpur","RM 2,400,000",4,3.0,NaN,2-sty Terrace/Link House,Land area : 3477 sq. ft.,Partly Furnished
47399,"Jinjang, Kuala Lumpur","RM 145,000",3,2.0,NaN,Flat (Intermediate),Built-up : 650 sq. ft.,Partly Furnished
47922,"Jinjang, Kuala Lumpur","RM 178,000",3,2.0,NaN,Flat (Intermediate),Built-up : 650 sq. ft.,Partly Furnished
48110,"Jinjang, Kuala Lumpur","RM 485,000",3,2.0,2.0,Serviced Residence,NaN,NaN
48852,"Jinjang, Kuala Lumpur","RM 1,175,000",4,3.0,2.0,2-sty Terrace/Link House,Land area : 1500 sq. ft.,Partly Furnished
48970,"Jinjang, Kuala Lumpur","RM 360,000",4,3.0,NaN,Cluster House (Corner),"Built-up : 1,313 sq. ft.",NaN
51779,"Jinjang, Kuala Lumpur","RM 1,300,000",5+1,4.0,NaN,2.5-sty Terrace/Link House,Land area : 22x75 sq. ft.,NaN
53747,"Jinjang, Kuala Lumpur","RM 580,000",6+1,2.0,4.0,1-sty Terrace/Link House (Intermediate),Land area : 30x90 sq. ft.,Unfurnished

In [174]:
#Gombak cluster

gbk = all_nan[all_nan['Location'].str.contains('Gombak')]
gbk

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
4521,"Gombak, Kuala Lumpur","RM 1,280,000",5,4.0,NaN,3-sty Terrace/Link House,Land area : 20x85 sq. ft.,NaN
18181,"Gombak, Kuala Lumpur","RM 1,790,000",5,5.0,NaN,Semi-detached House,Land area : 1755 sq. ft.,Unknown
24119,"Gombak, Kuala Lumpur","RM 900,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x70 sq. ft.,Fully Furnished
27748,"Gombak, Kuala Lumpur","RM 680,000",5,4.0,NaN,2.5-sty Terrace/Link House,Land area : 20x70 sq. ft.,Fully Furnished
31084,"Gombak, Kuala Lumpur","RM 3,000,000",7,5.0,4.0,Bungalow (EndLot),Land area : 7600 sq. ft.,Partly Furnished
31538,"Gombak, Kuala Lumpur","RM 1,144,000",1,1.0,6.0,Bungalow Land (Intermediate),Land area : 8800 sq. ft.,Unfurnished
42091,"Gombak, Kuala Lumpur","RM 365,000",3,2.0,NaN,2-sty Terrace/Link House,Land area : 16x55 sq. ft.,Partly Furnished
50841,"Gombak, Kuala Lumpur","RM 870,000",4,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 1400 sq. ft.,Partly Furnished
53480,"Gombak, Kuala Lumpur","RM 1,280,000",6,4.0,NaN,3-sty Terrace/Link House (Intermediate),Land area : 1400 sq. ft.,Partly Furnished

In [176]:
#The Mines cluster

tm = all_nan[all_nan['Location'].str.contains('Mines')]
tm

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
6814,"The Mines Resort, Kuala Lumpur","RM 20,000,000",7+1,7.0,NaN,Bungalow (Intermediate),Land area : 31000 sq. ft.,Fully Furnished

In [178]:
#Sri Kembangan cluster

skbgn = all_nan[all_nan['Location'].str.contains('Kembangan')]
skbgn

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
6819,"Sri Kembangan, Kuala Lumpur","RM 11,000,000",NaN,NaN,NaN,Bungalow Land (Corner),Land area : 18330 sq. ft.,Unfurnished
14597,"Seri Kembangan, Kuala Lumpur","RM 6,990,000",5+2,9.0,NaN,Bungalow,Land area : 7175 sq. ft.,Fully Furnished

In [181]:
#Tmn Duta cluster

td = all_nan[all_nan['Location'].str.contains('Taman Duta')]
td

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
7250,"Taman Duta, Kuala Lumpur","RM 15,000,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 30000 sq. ft.,Unfurnished
7251,"Taman Duta, Kuala Lumpur","RM 25,327,500",NaN,NaN,NaN,Residential Land (Corner),Land area : 50655 sq. ft.,Unfurnished
7252,"Taman Duta, Kuala Lumpur","RM 47,000,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 140000 sq. ft.,Unfurnished
7253,"Taman Duta, Kuala Lumpur","RM 9,900,000",7,7.0,4.0,Bungalow (Corner),Land area : 18700 sq. ft.,Partly Furnished
7254,"Taman Duta, Kuala Lumpur","RM 29,000,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 49000 sq. ft.,Unfurnished
8004,"Taman Duta, Kuala Lumpur","RM 10,000,000",4+1,4.0,NaN,Bungalow,Land area : 23000 sq. ft.,Partly Furnished
8084,"Taman Duta, Kuala Lumpur","RM 10,000,000",3+1,4.0,NaN,Bungalow Land,Land area : 22550 sq. ft.,Partly Furnished
8085,"Taman Duta, Kuala Lumpur","RM 10,000,000",3+1,4.0,NaN,Bungalow,Land area : 22550 sq. ft.,Partly Furnished
13351,"Taman Duta, Kuala Lumpur","RM 10,355,520",NaN,NaN,NaN,Bungalow Land (Intermediate),Land area : 15008 sq. ft.,NaN
13379,"Taman Duta, Kuala Lumpur","RM 3,800,000",5,5.0,3.0,3-sty Terrace/Link House (Corner),Land area : 4400 sq. ft.,Partly Furnished
16382,"Taman Duta, Kuala Lumpur","RM 55,000,000",NaN,NaN,NaN,Residential Land,Land area : 140000 sq. ft.,NaN
17125,"Taman Duta, Kuala Lumpur","RM 28,000,000",5+2,8.0,5.0,Bungalow,Land area : 15000 sq. ft.,Partly Furnished
17126,"Taman Duta, Kuala Lumpur","RM 13,800,000",6+1,8.0,10.0,Bungalow (Corner),Land area : 18000 sq. ft.,Partly Furnished
21101,"Taman Duta, Kuala Lumpur","RM 1,980,000,000",3,4.0,2.0,Condominium,"Built-up : 2,831 sq. ft.",NaN
23104,"Taman Duta, Kuala Lumpur",NaN,5+1,6.0,NaN,Bungalow (Intermediate),Land area : 25000 sq. ft.,Unfurnished
24880,"Taman Duta, Kuala Lumpur","RM 2,900,000",3,4.0,NaN,Condominium (Corner),"Built-up : 3,200 sq. ft.",Partly Furnished
25140,"Taman Duta, Kuala Lumpur","RM 6,400,000",NaN,NaN,NaN,Residential Land,Land area : 18687 sq. ft.,NaN
25304,"Taman Duta, Kuala Lumpur","RM 8,500,000",4+1,6.0,6.0,Bungalow,Land area : 10000 sq. ft.,Partly Furnished
26009,"Taman Duta, Kuala Lumpur","RM 46,800,000",NaN,NaN,NaN,Residential Land,Land area : 3.1 acres,NaN
26452,"Taman Duta, Kuala Lumpur","RM 28,000,000",7+,6.0,8.0,Bungalow (Intermediate),Land area : 15000 sq. ft.,Partly Furnished
27394,"Taman Duta, Kuala Lumpur","RM 11,500,000",6+,11.0,NaN,Bungalow,Land area : 17728 sq. ft.,Partly Furnished
29271,"Taman Duta, Kuala Lumpur","RM 8,000,000",7,7.0,NaN,Bungalow,Land area : 18687 sq. ft.,NaN
29458,"Taman Duta, Kuala Lumpur","RM 10,730,000",NaN,NaN,NaN,Residential Land,Land area : 37000 sq. ft.,NaN
29841,"Taman Duta, Kuala Lumpur","RM 23,000,000",7+1,6.0,NaN,Bungalow,Land area : 32000 sq. ft.,Partly Furnished
32390,"Taman Duta, Kuala Lumpur","RM 23,000,000",5+2,6.0,6.0,Bungalow,Land area : 20000 sq. ft.,Partly Furnished
33382,"Taman Duta, Kuala Lumpur","RM 23,000,000",4+1,4.0,NaN,Bungalow (Corner),Land area : 34018 sq. ft.,Partly Furnished
33552,"Taman Duta, Kuala Lumpur","RM 16,000,000",6+1,8.0,2.0,Bungalow,Land area : 18000 sq. ft.,Partly Furnished
36025,"Taman Duta, Kuala Lumpur","RM 16,000,000",6+1,8.0,NaN,Bungalow (EndLot),Land area : 18000 sq. ft.,Partly Furnished
38211,"Taman Duta, Kuala Lumpur","RM 12,000,000",5,6.0,NaN,Bungalow,Land area : 21000 sq. ft.,Partly Furnished
39513,"Taman Duta, Kuala Lumpur","RM 7,500,000",NaN,NaN,NaN,Residential Land,Land area : 22044 sq. ft.,NaN
44734,"Taman Duta, Kuala Lumpur","RM 28,000,000",5+2,8.0,NaN,Bungalow,Land area : 15000 sq. ft.,Partly Furnished
45406,"Taman Duta, Kuala Lumpur","RM 2,000,000",3,4.0,2.0,Condominium,"Built-up : 3,000 sq. ft.",NaN
46175,"Taman Duta, Kuala Lumpur","RM 2,800,000",6,6.0,NaN,Bungalow,Land area : 11000 sq. ft.,Unfurnished
47082,"Taman Duta, Kuala Lumpur","RM 18,000,000",6+1,6.0,8.0,Bungalow (Corner),Land area : 39000 sq. ft.,Partly Furnished
49568,"Taman Duta, Kuala Lumpur","RM 13,195,000",5+1,5.0,NaN,Bungalow (Corner),Land area : 37700 sq. ft.,Partly Furnished
49956,"Taman Duta, Kuala Lumpur","RM 2,490,000",4+1,4.0,5.0,Condominium (Penthouse),"Built-up : 2,800 sq. ft.",Partly Furnished
51174,"Taman Duta, Kuala Lumpur","RM 10,000,000",7,7.0,4.0,Bungalow,Land area : 18687 sq. ft.,Partly Furnished
51996,"Taman Duta, Kuala Lumpur","RM 28,000,000",4+2,NaN,NaN,Bungalow Land (EndLot),Land area : 52000 sq. ft.,NaN
52004,"Taman Duta, Kuala Lumpur","RM 28,000,000",4+2,NaN,NaN,Residential Land (EndLot),Land area : 52000 sq. ft.,NaN
52629,"Taman Duta, Kuala Lumpur","RM 14,800,000",8+1,9.0,6.0,Bungalow (Corner),Land area : 11981 sq. ft.,Unfurnished
52634,"Taman Duta, Kuala Lumpur","RM 7,200,000",4+1,4.0,6.0,Bungalow (Intermediate),Land area : 18309 sq. ft.,Partly Furnished
52635,"Taman Duta, Kuala Lumpur","RM 8,000,000",4+1,4.0,6.0,Bungalow (Intermediate),Land area : 15468 sq. ft.,Partly Furnished

In [183]:
#Happy Garden cluster

hg = all_nan[all_nan['Location'].str.contains('Garden')]
hg

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
7780,"Happy Garden, Kuala Lumpur","RM 1,480,000",6,NaN,NaN,3.5-sty Terrace/Link House,Land area : 20x70 sq. ft.,Partly Furnished
7798,"Happy Garden, Kuala Lumpur","RM 1,650,000",4,4.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x80 sq. ft.,Partly Furnished

In [185]:
#Pandan Jaya cluster

pj = all_nan[all_nan['Location'].str.contains('Pandan Jaya')]
pj

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
8240,"Pandan Jaya, Kuala Lumpur","RM 430,000",2,2.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 14x55 sq. ft.,Partly Furnished
8371,"Pandan Jaya, Kuala Lumpur","RM 250,000",3,1.0,NaN,Apartment,NaN,NaN
10694,"Pandan Jaya, Kuala Lumpur","RM 360,000",3,2.0,1.0,2-sty Terrace/Link House (Intermediate),"Built-up : 1,000 sq. ft.",Partly Furnished
12316,"Pandan Jaya, Kuala Lumpur","RM 900,000",4,3.0,3.0,2-sty Terrace/Link House (EndLot),Land area : 2250 sq. ft.,Partly Furnished
13425,"Pandan Jaya, Kuala Lumpur","RM 1,550,000",5,4.0,NaN,Semi-detached House (Intermediate),Land area : 30 x 65 sq. ft.,Partly Furnished
13430,"Pandan Jaya, Kuala Lumpur","RM 1,600,000",4,4.0,NaN,Semi-detached House (Intermediate),Land area : 30 x 65 sq. ft.,Partly Furnished
21583,"Pandan Jaya, Kuala Lumpur","RM 840,000",4,3.0,2.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
22072,"Pandan Jaya, Kuala Lumpur","RM 900,000",6,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 3018 sq. ft.,Unknown
24766,"Pandan Jaya, Kuala Lumpur","RM 259,000",3,2.0,1.0,Apartment,Built-up : 877 sq. ft.,NaN
24976,"Pandan Jaya, Kuala Lumpur","RM 250,000",2+1,1.0,2.0,Apartment (Corner),Built-up : 800 sq. ft.,Unfurnished
25484,"Pandan Jaya, Kuala Lumpur","RM 950,000",4,3.0,4.0,2-sty Terrace/Link House (Corner),Land area : 40X75 sq. ft.,Unfurnished
25898,"Pandan Jaya, Kuala Lumpur","RM 280,000",3,2.0,NaN,Apartment (Intermediate),Built-up : 802 sq. ft.,Partly Furnished
26007,"Pandan Jaya, Kuala Lumpur","RM 265,000",3,1.0,1.0,Apartment (Intermediate),Land area : 877 sq. ft.,Unfurnished
27100,"Pandan Jaya, Kuala Lumpur","RM 355,000",3,2.0,NaN,2-sty Terrace/Link House,Land area : 14x50 sq. ft.,Partly Furnished
28913,"Pandan Jaya, Kuala Lumpur","RM 300,000",2,1.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 14x50 sq. ft.,Unfurnished
37913,"Pandan Jaya, Kuala Lumpur","RM 138,000",2,1.0,NaN,Apartment,Built-up : 683 sq. ft.,NaN
38301,"Pandan Jaya, Kuala Lumpur","RM 1,480,000",4,5.0,2.0,Cluster House,Land area : 30X65 sq. ft.,Partly Furnished
42949,"Pandan Jaya, Kuala Lumpur","RM 1,400,000",5+1,3.0,3.0,2-sty Terrace/Link House (Corner),NaN,Fully Furnished
43994,"Pandan Jaya, Kuala Lumpur","RM 205,000",3,1.0,NaN,Apartment (Corner),Land area : 650 sq. ft.,Partly Furnished
45677,"Pandan Jaya, Kuala Lumpur","RM 430,000",2,2.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 700 sq. ft.,Partly Furnished
45778,"Pandan Jaya, Kuala Lumpur","RM 1,580,000",5,4.0,2.0,Semi-detached House (Intermediate),Land area : 30x65 sq. ft.,Partly Furnished
45989,"Pandan Jaya, Kuala Lumpur","RM 600,000",3,2.0,NaN,Bungalow,Land area : 3560 sq. ft.,NaN
47268,"Pandan Jaya, Kuala Lumpur","RM 250,000",2+1,2.0,NaN,Apartment,Built-up : 800 sq. ft.,Partly Furnished
51531,"Pandan Jaya, Kuala Lumpur","RM 350,000",3,2.0,2.0,Townhouse (Intermediate),Built-up : 850 sq. ft.,Partly Furnished
51853,"Pandan Jaya, Kuala Lumpur","RM 465,000",NaN,NaN,NaN,Residential Land,Land area : 3433.69 sq. ft.,NaN

In [187]:
#Sg Penchala cluster

sp = all_nan[all_nan['Location'].str.contains('Penchala')]
sp

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
11199,"Sungai Penchala, Kuala Lumpur","RM 8,126,250",NaN,NaN,NaN,Residential Land,Land area : 1.25 acres,NaN
11281,"Sungai Penchala, Kuala Lumpur","RM 3,590,840",NaN,NaN,NaN,Residential Land,Land area : 44885.5 sq. ft.,NaN
11906,"Sungai Penchala, Kuala Lumpur","RM 5,500,000",7,10.0,7.0,Bungalow (Intermediate),Land area : 11600 sq. ft.,Unfurnished
12017,"Sungai Penchala, Kuala Lumpur","RM 8,126,250",NaN,NaN,NaN,Residential Land,Land area : 54175 sq. ft.,NaN
12402,"Sungai Penchala, Kuala Lumpur","RM 3,250,000",5+1,4.0,3.0,Semi-detached House (Corner),Land area : 5512 sq. ft.,Fully Furnished
12403,"Sungai Penchala, Kuala Lumpur","RM 2,500,000",5+1,4.0,3.0,Semi-detached House (Intermediate),Land area : 4000 sq. ft.,Unfurnished
12491,"Sungai Penchala, Kuala Lumpur","RM 1,593,540",NaN,NaN,NaN,Bungalow Land,Land area : 8853 sq. ft.,NaN
19332,"Sungai Penchala, Kuala Lumpur","RM 2,100,000",NaN,NaN,NaN,Semi-detached House,Land area : 3283 sq. ft.,NaN
19479,"Sungai Penchala, Kuala Lumpur","RM 960,000",NaN,NaN,NaN,Bungalow Land,Land area : 6000 sq. ft.,NaN
19879,"Sungai Penchala, Kuala Lumpur","RM 2,529,244",5+1,4.0,NaN,Semi-detached House,Land area : 4015 sq. ft.,Partly Furnished
23833,"Sungai Penchala, Kuala Lumpur","RM 21,000,000",NaN,NaN,NaN,Bungalow,Land area : 87000 sq. ft.,NaN
24174,"Sungai Penchala, Kuala Lumpur","RM 9,100,000",NaN,NaN,NaN,Residential Land,Land area : 87120 sq. ft.,NaN
27744,"Sungai Penchala, Kuala Lumpur","RM 1,960,000",NaN,NaN,NaN,Residential Land,Land area : 43560 sq. ft.,NaN
27853,"Sungai Penchala, Kuala Lumpur","RM 4,550,000",6+1,7.0,NaN,Bungalow,Land area : 9100 sq. ft.,NaN
28671,"Sungai Penchala, Kuala Lumpur","RM 1,400,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 8000 sq. ft.,NaN
30616,"Sungai Penchala, Kuala Lumpur","RM 999,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 6500 sq. ft.,NaN
30971,"Sungai Penchala, Kuala Lumpur","RM 1,550,000",NaN,NaN,NaN,Bungalow Land (Intermediate),Land area : 8800 sq. ft.,NaN
33278,"Sungai Penchala, Kuala Lumpur","RM 2,500,000",5+1,4.0,4.0,Semi-detached House,Land area : 4100 sq. ft.,Unfurnished
33963,"Sungai Penchala, Kuala Lumpur","RM 2,500,000",5+1,4.0,4.0,Semi-detached House (Intermediate),Land area : 4015 sq. ft.,Partly Furnished
35819,"Sungai Penchala, Kuala Lumpur","RM 3,500,000",NaN,NaN,NaN,Residential Land,Land area : 32668 sq. ft.,Unknown
36293,"Sungai Penchala, Kuala Lumpur","RM 4,500,000",7,9.0,NaN,Bungalow,Land area : 9100 sq. ft.,Partly Furnished
36369,"Sungai Penchala, Kuala Lumpur","RM 2,350,000",NaN,NaN,NaN,Bungalow Land,Land area : 8761 sq. ft.,NaN
36370,"Sungai Penchala, Kuala Lumpur","RM 2,456,190",NaN,NaN,NaN,Bungalow Land,Land area : 11164.5 sq. ft.,NaN
36372,"Sungai Penchala, Kuala Lumpur","RM 1,593,540",NaN,NaN,NaN,Bungalow Land,Land area : 8853 sq. ft.,NaN
36373,"Sungai Penchala, Kuala Lumpur","RM 1,918,890",NaN,NaN,NaN,Bungalow Land,Land area : 9583 sq. ft.,NaN
36705,"Sungai Penchala, Kuala Lumpur","RM 1,960,000",NaN,NaN,NaN,Bungalow Land,Land area : 43560 sq. ft.,NaN
36804,"Sungai Penchala, Kuala Lumpur","RM 3,949,880",NaN,NaN,NaN,Residential Land,Land area : 17954 sq. ft.,NaN
36923,"Sungai Penchala, Kuala Lumpur","RM 1,000,000",NaN,2.0,NaN,Residential Land,Land area : 6500 sq. ft.,NaN
37107,"Sungai Penchala, Kuala Lumpur","RM 1,350,000",NaN,NaN,NaN,Residential Land (EndLot),Land area : 8000 sq. ft.,NaN
37108,"Sungai Penchala, Kuala Lumpur","RM 1,550,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 9000 sq. ft.,NaN
37512,"Sungai Penchala, Kuala Lumpur","RM 2,500,000",5+1,5.0,NaN,Semi-detached House,Land area : 7000 sq. ft.,NaN
37756,"Sungai Penchala, Kuala Lumpur","RM 2,975,582",5+1,4.0,1.0,Semi-detached House (EndLot),Land area : 4015 sq. ft.,Unfurnished
38545,"Sungai Penchala, Kuala Lumpur","RM 1,244,000",NaN,NaN,NaN,Residential Land,Land area : 8294 sq. ft.,NaN
38766,"Sungai Penchala, Kuala Lumpur","RM 1,244,000",NaN,NaN,NaN,Residential Land,Land area : 8294 sq. ft.,NaN
40232,"Sungai Penchala, Kuala Lumpur","RM 21,000,000",20 Above,20.0,NaN,Bungalow,Land area : 87120 sq. ft.,Partly Furnished
41470,"Sungai Penchala, Kuala Lumpur","RM 6,120,000",NaN,NaN,NaN,Residential Land,Land area : 42200 sq. ft.,NaN
41471,"Sungai Penchala, Kuala Lumpur","RM 12,000,000",NaN,NaN,NaN,Residential Land,Land area : 43560 sq. ft.,NaN
41472,"Sungai Penchala, Kuala Lumpur","RM 5,880,000",NaN,NaN,NaN,Residential Land,Land area : 39200 sq. ft.,NaN
41658,"Sungai Penchala, Kuala Lumpur","RM 2,600,000",5+1,4.0,4.0,Semi-detached House (Intermediate),"Built-up : 4,000 sq. ft.",Unfurnished
43494,"Sungai Penchala, Kuala Lumpur","RM 2,995,000",5+1,4.0,NaN,Semi-detached House,Land area : 4200 sq. ft.,NaN
43498,"Sungai Penchala, Kuala Lumpur","RM 5,500,000",12,9.0,8.0,Bungalow,"Built-up : 15,000 sq. ft.",NaN
43546,"Sungai Penchala, Kuala Lumpur","RM 1,360,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 6813.56 sq. ft.,NaN
43549,"Sungai Penchala, Kuala Lumpur","RM 4,400,000",NaN,NaN,NaN,Residential Land,Land area : 22485 sq. ft.,NaN
49022,"Sungai Penchala, Kuala Lumpur","RM 1,900,000",NaN,NaN,NaN,Bungalow Land (Corner),Land area : 17376 sq. ft.,Unknown
49910,"Sungai Penchala, Kuala Lumpur","RM 849,000",4+1,3.0,2.0,2.5-sty Terrace/Link House,Land area : 1851 sq. ft.,Partly Furnished

In [205]:
#Other cluster

other = all_nan[all_nan['Location'].str.contains('Other')]
other

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
2212,"Other, Kuala Lumpur","RM 2,300,000",NaN,NaN,NaN,Residential Land,Land area : 10000 sq. ft.,NaN
12359,"Other, Kuala Lumpur","RM 7,540,000",NaN,NaN,NaN,Residential Land,"Built-up : 19,848 sq. ft.",NaN
17047,"Other, Kuala Lumpur","RM 2,980,000",NaN,NaN,NaN,Residential Land,"Built-up : 31,382 sq. ft.",NaN
18183,"Other, Kuala Lumpur","RM 3,800,000",5+1,5.0,NaN,Semi-detached House,Land area : 8998 sq. ft.,Partly Furnished
21360,"Other, Kuala Lumpur","RM 1,800,000",4+1,5.0,NaN,3-sty Terrace/Link House,Land area : 22x85 sq. ft.,Fully Furnished
21655,"Other, Kuala Lumpur","RM 10,500,000",NaN,NaN,NaN,Bungalow,Land area : 15705 sq. ft.,NaN
21656,"Other, Kuala Lumpur","RM 10,500,000",NaN,NaN,NaN,Bungalow,Land area : 15705 sq. ft.,NaN
21690,"Other, Kuala Lumpur","RM 930,000",5,4.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 22x105 sq. ft.,Partly Furnished
23856,"Other, Kuala Lumpur","RM 2,540,000",6,6.0,2.0,Bungalow,Land area : 10239 sq. ft.,Unfurnished
29327,"Other, Kuala Lumpur","RM 12,800,000",NaN,NaN,NaN,Residential Land,Land area : 66000 sq. ft.,NaN
33072,"Other, Kuala Lumpur","RM 3,300,000",7+1,8.0,4.0,Bungalow (Corner),Land area : 5000 sq. ft.,Fully Furnished
33753,"Other, Kuala Lumpur","RM 3,000,000",7+1,8.0,4.0,Bungalow (Corner),Land area : 5000 sq. ft.,Partly Furnished
34890,"Other, Kuala Lumpur","RM 1,500,000",3+1,3.0,NaN,Semi-detached House (Corner),Land area : 4710 sq. ft.,Unfurnished
34906,"Other, Kuala Lumpur","RM 1,540,000",NaN,NaN,NaN,Residential Land (Intermediate),Land area : 8805 sq. ft.,Unfurnished
37285,"Other, Kuala Lumpur","RM 1,350,000",6,5.0,2.0,3.5-sty Terrace/Link House (Intermediate),Land area : 20x70 sq. ft.,Partly Furnished
39376,"Other, Kuala Lumpur","RM 6,000,000",NaN,NaN,NaN,Residential Land,Land area : 8276 sq. ft.,NaN
41460,"Other, Kuala Lumpur","RM 6,000,000",NaN,NaN,NaN,Bungalow Land,Land area : 8276 sq. ft.,NaN
41929,"Other, Kuala Lumpur","RM 880,000",4,3.0,2.0,Semi-detached House,Land area : 2625 sq. ft.,Unfurnished
42905,"Other, Kuala Lumpur","RM 1,000,000",NaN,NaN,NaN,3-sty Terrace/Link House,Land area : 1754 sq. ft.,NaN
44676,"Other, Kuala Lumpur","RM 730,000",3+1,3.0,3.0,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
48358,"Other, Kuala Lumpur","RM 3,300,000",7,7.0,NaN,Semi-detached House (Corner),Land area : 3584 sq. ft.,Partly Furnished
48748,"Other, Kuala Lumpur","RM 4,264,920",7+1,8.0,4.0,Bungalow (Corner),"Built-up : 5,900 sq. ft.",Unfurnished
49189,"Other, Kuala Lumpur","RM 1,100,000",4,3.0,NaN,3.5-sty Terrace/Link House,"Built-up : 2,770 sq. ft.",Unfurnished

In [229]:
#u-thant cluster

ut = all_nan[all_nan['Location'].str.contains('U-THANT|U-Thant') == True]
ut

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
8632,"U-THANT, Kuala Lumpur","RM 23,000,000",6+1,5.0,NaN,Bungalow (Intermediate),Land area : 22000 sq. ft.,Unfurnished
38695,"Jalan U-Thant, Kuala Lumpur","RM 8,280,000",4+2,5.0,4.0,3.5-sty Terrace/Link House (EndLot),"Built-up : 5,500 sq. ft.",Partly Furnished

In [234]:
all_nan = kl_house[kl_house['Location'].str.contains('Petaling Jaya|Singapore|cyberjaya|Rawang|Tijani|Sd|Ukay Heights|cheras perdana|Long|Kemensah|Canary|Taming Jaya')==False]
all_nan

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
0,"KLCC, Kuala Lumpur","RM 1,250,000",2+1,3.0,2.0,Serviced Residence,"Built-up : 1,335 sq. ft.",Fully Furnished
1,"Damansara Heights, Kuala Lumpur","RM 6,800,000",6,7.0,NaN,Bungalow,Land area : 6900 sq. ft.,Partly Furnished
2,"Dutamas, Kuala Lumpur","RM 1,030,000",3,4.0,2.0,Condominium (Corner),"Built-up : 1,875 sq. ft.",Partly Furnished
3,"Cheras, Kuala Lumpur",NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Bukit Jalil, Kuala Lumpur","RM 900,000",4+1,3.0,2.0,Condominium (Corner),"Built-up : 1,513 sq. ft.",Partly Furnished
...,...,...,...,...,...,...,...,...
53878,"Bangsar, Kuala Lumpur","RM 5,100,000",5+1,4.0,NaN,Bungalow (Corner),Land area : 7168 sq. ft.,Fully Furnished
53879,"Bangsar, Kuala Lumpur","RM 5,000,000",5,4.0,NaN,Bungalow (Intermediate),Land area : 15000 sq. ft.,Unfurnished
53880,"Bangsar, Kuala Lumpur","RM 5,500,000",5+1,4.0,NaN,Bungalow (Intermediate),Land area : 7168 sq. ft.,Partly Furnished
53881,"Wangsa Maju, Kuala Lumpur","RM 480,000",3,2.0,NaN,Condominium (Intermediate),"Built-up : 1,150 sq. ft.",Unfurnished
53882,"Setapak, Kuala Lumpur","RM 540,000",4,2.0,3.0,Condominium (Intermediate),"Built-up : 1,313 sq. ft.",Partly Furnished

In [235]:
checkleft = all_nan[all_nan['Location'].str.contains('KLCC|Klcc|Damansara Heights|Country Heights Damansara|Dutamas|Bukit Jalil|Taman Tun Dr Ismail|Cheras|Seputeh|Sri Petaling|Ampang Hilir|Bukit Tunku|Kiara|Desa ParkCity|Bangsar South|Sungai Besi|Klang Lama|Kepong|kepong|Kuching|KL City|Melawati|Casa Rimba|Sentul|Sentral|Setapak|Bangsar|City Centre|Bintang|Kuchai Lama|Taman Desa|Segambut|Caves|Wangsa Maju|OUG|Yarl|Hartamas|Sultan Ismail|Chan|Eco|Ampang|Setiawangsa|Menjalara|Sunway SPK|Pantai|Ipoh|Mid|Brickfields|Desa Pandan|Keramat|Pandan Indah|Federal|Desa Petaling|Pandan Perdana|Damai Perdana|Puchong|Salak|Titiwangsa|Damansara|Bandar Sri Damansara|Sri damansara|Tasik Selatan|Alam Damai|Ledang|Jinjang|Gombak|Mines|Kembangan|Taman Duta|Garden|Pandan Jaya|Penchala|Other|U-THANT|U-Thant') == False]
checkleft

,Location,Price,Rooms,Bathrooms,Car Parks,Property Type,Size,Furnishing
3313,"SEMARAK, Kuala Lumpur","RM 3,500,000",6+1,5.0,NaN,Bungalow,Land area : 7980 sq. ft.,Unfurnished
10790,"Taman TAR, Kuala Lumpur","RM 3,150,000",7+1,6.0,4.0,Bungalow,Land area : 8400 sq. ft.,Unfurnished
11925,"TAMAN MELATI, Kuala Lumpur","RM 1,330,000",4,3.0,NaN,2-sty Terrace/Link House (Corner),Land area : 42x75 sq. ft.,Unfurnished
12399,"Off Gasing Indah,, Kuala Lumpur","RM 7,500,000",NaN,NaN,NaN,Residential Land (Corner),Land area : 19741 sq. ft.,Unfurnished
17207,Kuala Lumpur,"RM 758,000",5,3.0,1.0,2-sty Terrace/Link House,Land area : 22x65 sq. ft.,Partly Furnished
18076,"Taman Wangsa Permai, Kuala Lumpur","RM 850,000",4,4.0,NaN,2.5-sty Terrace/Link House (Intermediate),Land area : 1500 sq. ft.,Fully Furnished
22981,"Bukit Persekutuan, Kuala Lumpur","RM 15,000,000",5+2,5.0,NaN,Bungalow (Intermediate),Land area : 5000 sq. ft.,Partly Furnished
24954,"Taman Ibukota, Kuala Lumpur","RM 2,500,000",5,4.0,4.0,Bungalow,Land area : 5700 sq. ft.,Partly Furnished
25953,"SANTUARI PARK PANTAI, Kuala Lumpur","RM 4,100,000",5,5.0,2.0,Bungalow,Land area : 6000 sq. ft.,NaN
34899,"Gurney, Kuala Lumpur","RM 4,700,000",5+2,5.0,5.0,Bungalow (Corner),Land area : 8700 sq. ft.,Partly Furnished
37158,"taman connaught, Kuala Lumpur","RM 768,000",5,3.0,NaN,2-sty Terrace/Link House (Intermediate),Land area : 22x75 sq. ft.,Partly Furnished
40352,"SANTUARI PARK PANTAI, Kuala Lumpur","RM 7,008,000",5,5.0,NaN,Bungalow,"Built-up : 7,266 sq. ft.",NaN
41567,"duta Nusantara, Kuala Lumpur","RM 4,450,000",5+1,6.0,4.0,Semi-detached House (Intermediate),Land area : 4000 sq. ft.,Partly Furnished
41886,Kuala Lumpur,"RM 990,000",5,5.0,4.0,2-sty Terrace/Link House (Intermediate),NaN,Partly Furnished
53664,"Kuala Lumpur, Kuala Lumpur","RM 3,300,000",7+1,8.0,NaN,Semi-detached House,"Land area : 10,000 sq. ft.",NaN